"""Fixed profiling script: raw data in, dataset card out. Runs as a subprocess.

This file is *not* generated by an LLM, and it is the only place besides
``scripts/train.py`` that opens the data file. Because both run in a child process,
the orchestrator process — the one that renders prompts — never holds a data row.

Emission policy
---------------
The card is what the reasoning nodes get to see, so every field below is an
aggregate over a whole column that cannot be inverted back to a record.

EMIT   row/column counts, missing rates, class rates, distinct-count buckets,
       skew / magnitude / correlation buckets, outlier rates, column names, dtypes,
       reference-baseline holdout scores and their bootstrap intervals, the baseline
       ranking's KS, the encoding report, the split protocol, suspected missing-codes
       and the operator's caveats
NEVER  cell values, min/max, mean/std/quantiles, class labels, example rows

Four entries look like exceptions to that policy and none is:

* a **suspected sentinel** publishes a *value*, but only one this repo's own constant list
  already held, so what the data contributed is the rate
  (:mod:`automl_agent.dataset.sentinels`);
* a **``--caveat``** publishes free text, typed by a human about their own data rather than
  lifted from a row by any code path here (:mod:`automl_agent.dataset.caveats`);
* **baseline scores, the KS, and ``baseline.ci``** are holdout aggregates, in policy for the reason
  training metrics are, and here because the goal threshold is derived from all three: the score
  sets the bar (:mod:`automl_agent.scoring.goal`), the KS fixes what any cut of that ranking can
  reach (:mod:`automl_agent.scoring.ranking`), and the interval says whether a bar sits inside the
  noise of the number it came from (:mod:`automl_agent.scoring.intervals`);
* the **``data`` block** carries the file path so the executor can find it again, and is
  private — :func:`automl_agent.privacy.public_card` strips it before the card enters state.

Buckets rather than numbers for scale and skew because a planner needs to know a column is
heavy-tailed and lives in the hundreds, not that patient 3's creatinine was 4.1 — and a min/max
pair *is* two real patients' values.

Contract
--------
Input  : ``--data <csv> --target <column> --out <card.json>``
Output : the card at ``--out``; a human summary on stdout; exit 0 on success, 1 on
         failure (the caller shows stderr, which stays local and is never prompted).
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path
from typing import Any

# The node runs this file by path, not as a package module, so the repo root is not on
# sys.path and a relative import is impossible. Adding it is what lets the two processes
# share one metric registry instead of each keeping its own list.
if __package__ in (None, ""):  # pragma: no cover - only when run as a file
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from automl_agent.dataset.caveats import (  # noqa: E402 - needs the path fix above
    CAVEATS_KEY,
    card_caveats,
    grouping_caveats,
    merge_caveats,
    sentinel_caveats,
)
from automl_agent.dataset.features import (  # noqa: E402 - needs the path fix above
    describe_encoding,
    encode_features,
    is_encodable_column,
    is_numeric_column,
)
from automl_agent.dataset.sentinels import (  # noqa: E402 - needs the path fix above
    describe_sentinels,
    detect_sentinels,
)
from automl_agent.dataset.targets import (  # noqa: E402 - needs the path fix above
    DEFAULT_TARGET_MISSING_POLICY,
    TARGET_MISSING_POLICIES,
    detect_task,
    encode_target,
)
from automl_agent.scoring.intervals import (  # noqa: E402 - needs the path fix above
    CI_LEVEL,
    DEFAULT_RESAMPLES,
    bootstrap_interval,
)
from automl_agent.scoring.metrics import (  # noqa: E402 - needs the path fix above
    ALIASES,
    METRICS,
    TASK_CLASSIFICATION,
    TASK_REGRESSION,
)
from automl_agent.scoring.ranking import (  # noqa: E402 - needs the path fix above
    best_cut_ceiling,
    ks_statistic,
)
from automl_agent.scoring.splits import (  # noqa: E402 - needs the path fix above
    describe_protocol,
    protocol,
    split_three_way,
)

# The one definition of "how each metric is computed". The baseline this script measures is
# the *bar* every trained attempt is compared against, so the two have to score identically;
# a second copy here is a comparison that could silently drift. train.py's module-level
# imports are pure-python package modules — sklearn arrives inside the branches — so this
# costs no import-time dependency this script does not already have.
from automl_agent.scripts.train import scorers  # noqa: E402 - needs the path fix above
from automl_agent.threads import thread_state  # noqa: E402 - needs the path fix above

# Bucket edges. Chosen to be coarse enough that no single record moves a bucket.
DISTINCT_EDGES: tuple[tuple[int, str], ...] = ((1, "constant"), (2, "binary"), (10, "low"), (100, "medium"))
SKEW_EDGES: tuple[tuple[float, str], ...] = ((0.5, "low"), (2.0, "moderate"))
MAGNITUDE_EDGES: tuple[tuple[float, str], ...] = (
    (1.0, "sub_unit"),
    (10.0, "unit"),
    (100.0, "tens"),
    (1000.0, "hundreds"),
)
CORRELATION_EDGES: tuple[tuple[float, str], ...] = ((0.05, "none"), (0.15, "weak"), (0.30, "moderate"))

DEFAULT_MEMORY_LIMIT_MB = 2048
DEFAULT_MAX_TRAIN_TIME_SEC = 600

# The reference baseline. Fixed so its score means the same thing across runs and
# across datasets: "what a competent default already gets here". One per task, and the
# regression side is Ridge for the same reason the classification side is LogisticRegression:
# a regularised linear model is the cheapest thing that is not a straw man, so beating it
# means something and failing to beat it is a finding.
BASELINE_MODELS: dict[str, str] = {
    TASK_CLASSIFICATION: "logreg (median impute + standard scale)",
    TASK_REGRESSION: "ridge (median impute + standard scale)",
}
BASELINE_ESTIMATORS: dict[str, str] = {
    TASK_CLASSIFICATION: "LogisticRegression",
    TASK_REGRESSION: "Ridge",
}
BASELINE_NOTE = (
    "{estimator} fitted on the training split and scored on the validation split "
    "of automl_agent.scoring.splits' protocol, seed {seed} — the same split scripts/train.py "
    "uses, so the numbers are directly comparable. The test slice is not read here."
)
# Profiling runs before the loop's time budget applies, so the baseline is capped
# rather than left to scale with the file.
BASELINE_MAX_ROWS = 50_000


def _bucket(value: float, edges: tuple[tuple[float, str], ...], last: str) -> str:
    for edge, label in edges:
        if value <= edge:
            return label
    return last


# --------------------------------------------------------------------------- #
# Column profiles
# --------------------------------------------------------------------------- #


def profile_column(series: Any, target: Any) -> dict[str, Any]:
    """One column's aggregate descriptors. No value from the column is returned."""
    import numpy as np
    import pandas as pd

    n_rows = int(len(series))
    n_missing = int(series.isna().sum())
    present = series.dropna()
    distinct = int(present.nunique())
    numeric = bool(pd.api.types.is_numeric_dtype(series)) and not bool(
        pd.api.types.is_bool_dtype(series)
    )

    profile: dict[str, Any] = {
        "name": str(series.name),
        "dtype": str(series.dtype),
        "missing_rate": round(n_missing / n_rows, 4) if n_rows else 0.0,
        "distinct": _bucket(distinct, DISTINCT_EDGES, "high"),
        # Asked of :mod:`automl_agent.dataset.features`, not decided here: a categorical column
        # narrow enough to one-hot is usable now, and only that module knows the cap.
        "usable_by_executor": (
            is_numeric_column(series) or is_encodable_column(series, distinct)
        ),
    }

    if distinct <= 1:
        profile["kind"] = "constant"
    elif distinct == 2:
        profile["kind"] = "binary"
    elif not numeric:
        # Categorical *labels* are cell values, so only the count leaves this function.
        profile["kind"] = "categorical"
    elif bool(pd.api.types.is_integer_dtype(series)) and distinct <= 20:
        profile["kind"] = "discrete"
    else:
        profile["kind"] = "continuous"

    # Above the aggregates below on purpose: every one of them — magnitude, skew,
    # outlier_rate, target_corr — is measured with these values still counted as
    # measurements, and nothing here converts them. See :mod:`automl_agent.dataset.sentinels`.
    suspects = detect_sentinels(series)
    if suspects:
        profile["sentinel_suspects"] = suspects

    if not numeric or len(present) < 8:
        return profile

    values = present.to_numpy(dtype="float64", copy=False)
    magnitude = float(np.median(np.abs(values)))
    profile["magnitude"] = _bucket(magnitude, MAGNITUDE_EDGES, "thousands+")
    profile["skew"] = _bucket(abs(float(pd.Series(values).skew() or 0.0)), SKEW_EDGES, "high")

    q1, q3 = (float(x) for x in np.percentile(values, [25, 75]))
    spread = q3 - q1
    if spread > 0:
        outliers = int(((values < q1 - 1.5 * spread) | (values > q3 + 1.5 * spread)).sum())
        profile["outlier_rate"] = round(outliers / len(values), 4)

    if target is not None:
        mask = present.index
        try:
            correlation = float(pd.Series(values, index=mask).corr(target.loc[mask]))
        except (ValueError, TypeError):  # pragma: no cover - degenerate columns
            correlation = float("nan")
        if correlation == correlation:  # not NaN
            profile["target_corr"] = _bucket(abs(correlation), CORRELATION_EDGES, "strong")
    return profile


# --------------------------------------------------------------------------- #
# Reference baseline
# --------------------------------------------------------------------------- #


def _mirror_aliases(scores: dict[str, float]) -> dict[str, float]:
    """Publish each score under its alias too, so either spelling reads the card."""
    for alias, target in ALIASES.items():
        if target in scores:
            scores[alias] = scores[target]
    return scores


def _score_all(
    y_true: Any, pred: Any, proba: Any, average: str, task: str = TASK_CLASSIFICATION
) -> dict[str, float]:
    """Score every registry metric this prediction can support.

    Driven by the registry rather than a hand-kept list: the baseline then covers exactly
    the metrics ``--metric`` accepts *for this task*, which is the property that makes an
    ``auto`` bar derivable for any of them.
    """
    thunks = scorers(y_true, pred, proba, average, task)
    scores: dict[str, float] = {}
    for name, spec in METRICS.items():
        if spec.task != task:
            continue
        scorer = thunks.get(name)
        if scorer is None:  # pragma: no cover - a registry entry with no scorer here
            continue
        if spec.binary_only and average != "binary":
            continue
        if spec.needs_proba and proba is None:
            continue
        # A single-class holdout has no AUC; the threshold metrics still have values.
        with contextlib.suppress(ValueError):
            scores[name] = round(float(scorer()), 4)
    return _mirror_aliases(scores)


def _baseline_intervals(
    y_true: Any,
    pred: Any,
    proba: Any,
    average: str,
    scores: dict[str, float],
    *,
    task: str = TASK_CLASSIFICATION,
    groups: Any = None,
    seed: int = 42,
    resamples: int = DEFAULT_RESAMPLES,
) -> dict[str, Any] | None:
    """A 95% bootstrap interval for every baseline score, or ``None`` if none is measurable.

    *Every* score, not just one: the card is written before ``--metric`` is chosen, so
    picking a single metric here would half the time be the wrong one. The cost is at most
    seven metrics times ``resamples`` over the validation slice, which is seconds on a
    profiling run that already fits a model.

    This is where the interval pays for itself, because the baseline is the *bar*: an
    ``auto`` threshold is derived from these numbers (:mod:`automl_agent.scoring.goal`), and a bar
    sitting inside the interval of the score it was derived from is a bar within the noise
    floor of this dataset's validation slice. ``goal.describe`` says so before the loop
    starts, which is one iteration budget cheaper than finding out afterwards.
    """
    bounds: dict[str, Any] = {}
    unit, drawn = "row", 0
    for name in METRICS:
        if name not in scores:
            continue

        def one(y_slice: Any, pred_slice: Any, proba_slice: Any, metric: str = name) -> float:
            return float(scorers(y_slice, pred_slice, proba_slice, average, task)[metric]())

        interval = bootstrap_interval(
            one, y_true, pred, proba, groups=groups, seed=seed, resamples=resamples
        )
        if interval is None:
            continue
        # Four decimals, like ``scores`` and ``chance``: the card's numbers are read side by
        # side, and a bound printed to six would claim a precision 400 resamples do not have.
        bounds[name] = {"low": round(interval.low, 4), "high": round(interval.high, 4)}
        unit, drawn = interval.unit, interval.resamples
    if not bounds:
        return None
    # Mirrored under the aliases, like ``scores`` and ``chance``, so a card read under
    # either spelling finds the same interval.
    for alias, target in ALIASES.items():
        if target in bounds:
            bounds[alias] = bounds[target]
    return {"level": CI_LEVEL, "unit": unit, "resamples": drawn, "scores": bounds}


def reference_scores(
    features: Any,
    codes: Any,
    n_classes: int,
    *,
    task: str = TASK_CLASSIFICATION,
    seed: int = 42,
    groups: Any = None,
    group_column: str | None = None,
    resamples: int = DEFAULT_RESAMPLES,
) -> dict[str, Any] | None:
    """Fit the fixed reference baseline and return its holdout scores.

    Also returns ``chance`` — a predictor that uses no feature at all, on the same split —
    because a baseline score is only interpretable next to it. On an 11%-positive cohort
    ``accuracy 0.89`` is chance, and a threshold derived from it would be a lie. The
    regression counterpart is the *mean* predictor, and it is the more important of the two:
    ``r2`` is defined against it (so chance is 0.0 by construction) and an ``mae`` is
    meaningless until you know what predicting the mean already costs.

    Returns ``None`` rather than raising: the card is the deliverable here, and a
    dataset the baseline cannot handle is exactly the kind the agent should still get
    to attempt.
    """
    import numpy as np
    from sklearn.impute import SimpleImputer
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler

    regression = task == TASK_REGRESSION
    if features.shape[1] == 0 or (not regression and n_classes < 2):
        return None

    x_arr = np.asarray(features.to_numpy(), dtype="float64")
    y_arr = np.asarray(codes, dtype="float64" if regression else None)
    group_arr = np.asarray(groups) if groups is not None else None
    if len(y_arr) > BASELINE_MAX_ROWS:
        x_arr, y_arr = x_arr[:BASELINE_MAX_ROWS], y_arr[:BASELINE_MAX_ROWS]
        if group_arr is not None:
            group_arr = group_arr[:BASELINE_MAX_ROWS]

    try:
        # The same three-way protocol train.py uses, from the same function. The test
        # slice is *ignored* here on purpose: the baseline is a validation-set score, like
        # every attempt's, and the test rows stay unread until the loop is over.
        splits = split_three_way(x_arr, y_arr, seed, groups=group_arr, stratify=not regression)
        x_train, y_train = splits.x_train, splits.y_train
        x_val, y_val = splits.x_val, splits.y_val
        if regression:
            from sklearn.dummy import DummyRegressor
            from sklearn.linear_model import Ridge

            estimator: Any = Ridge(random_state=seed)
            dummy: Any = DummyRegressor(strategy="mean")
        else:
            from sklearn.dummy import DummyClassifier
            from sklearn.linear_model import LogisticRegression

            estimator = LogisticRegression(max_iter=1000, random_state=seed)
            dummy = DummyClassifier(strategy="prior")
        model = Pipeline(
            [
                ("impute", SimpleImputer(strategy="median")),
                ("scale", StandardScaler()),
                ("model", estimator),
            ]
        )
        model.fit(x_train, y_train)
        dummy.fit(x_train, y_train)

        average = "binary" if not regression and n_classes == 2 else "macro"
        proba = (
            model.predict_proba(x_val)[:, 1] if not regression and n_classes == 2 else None
        )
        pred = model.predict(x_val)
        scores = _score_all(y_val, pred, proba, average, task)
        chance = _score_all(y_val, dummy.predict(x_val), None, average, task)
        # A prior-only predictor has no ranking information at all, by definition — so
        # its two ranking metrics are constants rather than something to measure. AUC is
        # 0.5; average precision of a constant ranker is the positive rate, which is why
        # a pr_auc bar has to be read against the class balance and not against 0.5.
        if not regression and n_classes == 2:
            chance["roc_auc"] = 0.5
            chance["pr_auc"] = round(float(np.mean(np.asarray(y_val) == 1)), 4)
            _mirror_aliases(chance)
    except (ValueError, MemoryError, ImportError) as exc:
        print(f"reference baseline skipped: {type(exc).__name__}: {exc}", flush=True)
        return None

    reference: dict[str, Any] = {
        "model": BASELINE_MODELS[task],
        "note": BASELINE_NOTE.format(estimator=BASELINE_ESTIMATORS[task], seed=seed),
        "n_rows_used": int(len(y_arr)),
        # Which rows produced these numbers. Published so the card can be *refused* when a
        # run's protocol disagrees with it, instead of silently comparing a bar derived
        # here against scores measured over different rows — automl_agent.scoring.splits.
        "protocol": protocol(seed, group_column, stratified=not regression),
        # Its neighbour above says which rows produced these numbers; this says which
        # environment did. Both are here for the same reason: in ``auto`` mode these scores
        # *are* the bar the loop is judged against, and a bar measured in one thread state
        # against attempts fitted in another is off by up to 0.0077 balanced_accuracy
        # (:mod:`automl_agent.threads`) — enough to decide whether iteration 1 already cleared
        # it. Costs four lines of the planning prompt, which is what ``protocol`` costs.
        "threads": thread_state(),
        "scores": scores,
        "chance": chance,
    }
    # The ranking's own limit, in policy for the same reason the scores are: a statistic
    # over the whole holdout. It is what tells the goal derivation that a bar is above
    # anything this ranking can reach at *any* cut — see automl_agent.scoring.ranking. There is no
    # ranking to measure without a probability, so a regression baseline has neither field.
    ks = ks_statistic(y_val, proba)
    ceiling = best_cut_ceiling(ks)
    if ks is not None and ceiling is not None:
        reference["ks"] = round(ks, 4)
        reference["balanced_accuracy_at_best_cut"] = ceiling
    # How much of each score above is the validation slice rather than the model. Grouped
    # when the split was grouped, because five visits of one patient are not five
    # observations — automl_agent.scoring.intervals.
    intervals = _baseline_intervals(
        y_val,
        pred,
        proba,
        average,
        scores,
        task=task,
        groups=splits.groups_val,
        seed=seed,
        resamples=resamples,
    )
    if intervals is not None:
        reference["ci"] = intervals
    return reference


# --------------------------------------------------------------------------- #
# Card assembly
# --------------------------------------------------------------------------- #


def _card_task(task: str, n_classes: int | None) -> str:
    """The card's own task label, which is finer than the registry's two.

    A plan prompt that reads ``binary_classification`` knows there is one positive class;
    ``classification`` alone does not say that. :data:`automl_agent.scoring.metrics.CARD_TASKS` maps
    these back onto the registry's pair, so the extra resolution costs no ambiguity.
    """
    if task == TASK_REGRESSION:
        return "regression"
    return "binary_classification" if n_classes == 2 else "multiclass_classification"


def target_profile(series: Any) -> dict[str, Any]:
    """The continuous target's shape, in the same buckets a feature column gets.

    Same function as the features, so the target is described in the same vocabulary and by
    the same privacy rule: buckets and rates, never a value. ``magnitude`` is the field that
    earns this block — an ``mae`` bar of 3.5 is meaningless until a reader knows whether the
    column runs in units or in thousands, and it is the only thing on the card that says so.

    ``usable_by_executor`` and ``name`` are dropped: the target is not a feature, and its
    name is already the card's ``target_column``.
    """
    profile = profile_column(series, None)
    return {
        key: value for key, value in profile.items() if key not in ("name", "usable_by_executor")
    }


def build_card(
    data_path: Path,
    target_column: str,
    *,
    name: str | None = None,
    memory_limit_mb: float = DEFAULT_MEMORY_LIMIT_MB,
    max_train_time_sec: float = DEFAULT_MAX_TRAIN_TIME_SEC,
    baseline: bool = True,
    seed: int = 42,
    on_missing_target: str = DEFAULT_TARGET_MISSING_POLICY,
    caveats: tuple[str, ...] | list[str] = (),
    group_column: str | None = None,
    bootstrap_resamples: int = DEFAULT_RESAMPLES,
) -> dict[str, Any]:
    """Read the data and return the card. The only function here that sees rows."""
    import pandas as pd

    frame = pd.read_csv(data_path)
    if target_column not in frame.columns:
        # The column names of a file the user chose are not raw data, and naming the
        # missing one is the whole diagnostic value of this error.
        raise ValueError(
            f"target_column {target_column!r} not found; available columns: "
            f"{sorted(str(c) for c in frame.columns)}"
        )
    if group_column:
        if group_column not in frame.columns:
            raise ValueError(
                f"group_column {group_column!r} not found; available columns: "
                f"{sorted(str(c) for c in frame.columns)}"
            )
        if group_column == target_column:
            raise ValueError(f"group_column {group_column!r} is the target column")

    target_raw = frame[target_column]
    # Dropped from the features, not only from the split: an id the estimator can read is
    # a shortcut to the label, and the profile of a ``subject_id`` column would be
    # published as though it were a predictor. train.py drops the same column.
    group_raw = frame[group_column] if group_column else None
    features = frame.drop(columns=[target_column] + ([group_column] if group_column else []))
    # Read off the column, not chosen: a continuous target category-coded into labels would
    # train a classifier on one "class" per row — see automl_agent.dataset.targets.detect_task.
    task = detect_task(target_raw)
    regression = task == TASK_REGRESSION
    codes, keep, n_missing_target = encode_target(target_raw, on_missing_target, task)
    if n_missing_target:
        # Filtered here so every number below — row count, missing rates, correlations,
        # the baseline — describes the same rows the trainer will use.
        features = features[keep]
        if group_raw is not None:
            group_raw = group_raw[keep]
        print(
            f"dropped {n_missing_target} rows with a missing target "
            f"({target_column!r}); {len(codes)} rows remain",
            flush=True,
        )
    # Class *labels* stay behind; only their frequencies are published, sorted so the
    # order carries no information about which label is which. A continuous target has no
    # frequencies to publish — its shape goes into the ``target`` block below instead.
    balance = (
        []
        if regression
        else sorted((codes.value_counts(normalize=True)).round(4).tolist(), reverse=True)
    )
    n_classes = None if regression else int(codes.nunique())

    # What ``target_corr`` in each column profile is measured against. A continuous target
    # is the case the field was always meant for; two classes coded 0/1 are the point-biserial
    # correlation, which is the same number. Three or more codes are not orderable, so there
    # is nothing to correlate and the field is absent.
    numeric_target = codes.astype("float64") if regression or n_classes == 2 else None
    profiles = [profile_column(features[column], numeric_target) for column in features.columns]
    usable = [item for item in profiles if item["usable_by_executor"]]

    # Printed before the baseline is fitted, so a reader meets the warning above the scores
    # it applies to rather than after them.
    suspects = {
        item["name"]: item["sentinel_suspects"]
        for item in profiles
        if item.get("sentinel_suspects")
    }
    warning = describe_sentinels(suspects)
    if warning:
        print(warning, flush=True)

    # The same encoding train.py performs, from the same function, so the baseline is
    # measured on exactly the feature matrix the agent's models will get.
    executor_features, encoding = encode_features(features)
    print(describe_encoding(encoding), flush=True)
    # Same normalisation train.py applies, so "one group" means the same thing in both
    # processes and the two split identically.
    group_values = (
        group_raw.astype("string").fillna("<missing>").to_numpy() if group_raw is not None else None
    )
    if group_values is not None:
        print(
            f"grouped by {group_column}: {len(set(group_values.tolist()))} distinct groups"
            f" over {len(group_values)} rows — no group is split across train/val/test",
            flush=True,
        )
    reference = (
        reference_scores(
            executor_features,
            codes,
            n_classes or 0,
            task=task,
            seed=seed,
            groups=group_values,
            group_column=group_column,
            resamples=bootstrap_resamples,
        )
        if baseline
        else None
    )

    card: dict[str, Any] = {
        "name": name or f"{target_column}-prediction",
        "description": (
            f"{data_path.suffix.lstrip('.') or 'csv'} 데이터에서 자동 생성된 카드입니다. "
            "원본 행은 이 카드에 포함되지 않습니다 — 모든 수치는 열 전체에 대한 집계입니다."
        ),
        "task": _card_task(task, n_classes),
        "target_column": target_column,
        # Rows the card actually describes: with a ``drop`` policy the unlabelled ones are
        # gone, and the executor will drop the same ones.
        "n_rows": int(len(codes)),
        "n_features": len(usable),
        # Kept under its original name so cards written before one-hot encoding existed
        # still read the same way; what it counts is unchanged — columns the executor
        # cannot use — but a narrow categorical is no longer one of them.
        "n_features_dropped_non_numeric": len(profiles) - len(usable),
        # What the estimators actually receive, which is no longer the column count: 9
        # numeric columns plus a 12-level month is 9 + 12. Disclosed because it is the
        # number the memory guard prices and the number a reader needs to tell "scored on
        # your data" from "scored on the numeric half of your data".
        "encoding": encoding,
        # ``None`` for a continuous target rather than absent, so a reader (and the goal
        # derivation) can tell "this card is about a regression" from "this card is old".
        "n_classes": n_classes,
        "class_balance": balance or None,
        "imbalance_ratio": round(balance[0] / balance[-1], 2) if balance and balance[-1] else None,
        "missing": {
            "overall_rate": round(float(features.isna().to_numpy().mean()), 4),
            "columns_with_missing": sum(1 for item in profiles if item["missing_rate"] > 0),
            "worst_rate": max((item["missing_rate"] for item in profiles), default=0.0),
        },
        "features": profiles,
        # Carried in the card so the trainer applies the same policy without being told
        # again, and so a reader can tell "8000 rows" from "8000 of 8012 rows".
        "target_missing": {"policy": on_missing_target, "n_dropped": int(n_missing_target)},
        "preprocessing": {"impute": "median", "scale": True},
        "constraints": {
            "memory_limit_mb": memory_limit_mb,
            "max_train_time_sec": max_train_time_sec,
        },
        "profile": {
            "generated_by": "automl_agent.scripts.profile",
            "policy": "aggregates only — no cell values, no min/max, no class labels",
        },
        # Private: stripped by privacy.public_card before the card enters state.
        # ``group_column`` lives here rather than in ``preprocessing`` for the reason
        # ``path`` does: it is a data-loading decision, and the plan the LLM writes must
        # not be able to change which rows are held out. See automl_agent.scoring.splits.
        "data": {"path": str(data_path), "target_column": target_column},
    }
    if regression:
        # What ``class_balance`` is for a classification card: the one block that says what
        # the numbers in the target's own units mean. Only on the regression path, because a
        # class-coded target's shape is its balance and that is already published above.
        card["target"] = target_profile(codes)
    if group_column:
        card["data"]["group_column"] = group_column
    # What the aggregates above cannot say, from the two sources that can: this script's own
    # checks and the operator's ``--caveat``. Machine findings first, because the human's
    # note is usually a comment on them. Absent rather than empty when there is nothing —
    # see automl_agent.dataset.caveats.
    notes = merge_caveats(
        sentinel_caveats(suspects),
        grouping_caveats(
            group_column, len(set(group_values.tolist())) if group_values is not None else None
        ),
        list(caveats),
    )
    if notes:
        card[CAVEATS_KEY] = notes
    if reference is not None:
        # What the goal threshold is derived from (automl_agent.scoring.goal), and what tells the
        # planner whether its first attempt actually beat a plain linear model.
        card["baseline"] = reference
    return card


def summarise(card: dict[str, Any]) -> str:
    """Human-readable digest for the console. Aggregates only, same as the card."""
    missing = card.get("missing") or {}
    worst = sorted(
        (item for item in card.get("features") or [] if item.get("missing_rate")),
        key=lambda item: -float(item["missing_rate"]),
    )[:5]
    target = card.get("target") or {}
    if card.get("task") == "regression":
        # No class counts to print; the scale and the shape are what a reader needs in
        # order to read the mae/rmse two blocks below at all.
        target_line = (
            f"  target={card['target_column']}  kind={target.get('kind')}"
            f"  magnitude={target.get('magnitude')}  skew={target.get('skew')}"
            f"  outlier_rate={target.get('outlier_rate')}"
        )
    else:
        target_line = (
            f"  target={card['target_column']}  n_classes={card['n_classes']}"
            f"  balance={card['class_balance']}  imbalance_ratio={card['imbalance_ratio']}"
        )
    lines = [
        f"dataset card: {card['name']} ({card['task']})",
        f"  rows={card['n_rows']}  features={card['n_features']}"
        f"  dropped_non_numeric={card['n_features_dropped_non_numeric']}",
        target_line,
        f"  missing: overall={missing.get('overall_rate')}"
        f" columns={missing.get('columns_with_missing')} worst={missing.get('worst_rate')}",
    ]
    declared = (card.get("baseline") or {}).get("protocol")
    if isinstance(declared, dict):
        # Printed above the baseline for the same reason it is in the card: the score two
        # lines down is a validation number, and one slice of the file is deliberately
        # not in it.
        lines.append("  " + describe_protocol(declared))
    encoding = card.get("encoding")
    if isinstance(encoding, dict):
        # The line the baseline below has to be read against: its scores are measured on
        # this matrix, not on the column list one line above.
        lines.append("  " + describe_encoding(encoding))
    dropped = int((card.get("target_missing") or {}).get("n_dropped") or 0)
    if dropped:
        lines.append(f"  target 결측 {dropped}행 제외 (--on-missing-target drop) — 위 수치는 남은 행 기준")
    if worst:
        lines.append(
            "  결측 상위: "
            + ", ".join(f"{item['name']}={item['missing_rate']}" for item in worst)
        )
    suspects = [item for item in card.get("features") or [] if item.get("sentinel_suspects")]
    if suspects:
        # Repeated here even though build_card already printed the long form: this digest is
        # what a human actually scans, and the line it sits next to — `결측 상위` — is the one
        # a sentinel makes a lie.
        lines.append(
            f"  결측 코드 의심 {len(suspects)}열: "
            + ", ".join(
                f"{item['name']}={item['sentinel_suspects'][0]['value']}" for item in suspects[:5]
            )
            + " (변환 안 함 — 위 경고 참고)"
        )
    notes = card_caveats(card)
    if notes:
        # Echoed in full so the operator can see that their ``--caveat`` landed, and read
        # the exact sentence every reasoning prompt of the run will carry.
        lines.append(f"  데이터 주의사항 {len(notes)}건 — 모든 추론 프롬프트에 그대로 실립니다:")
        lines.extend(f"    - {note}" for note in notes)
    reference = card.get("baseline")
    if isinstance(reference, dict):
        scores = reference.get("scores") or {}
        chance = reference.get("chance") or {}
        # Canonical names only. The card publishes each score under its aliases too, so
        # either spelling of ``--metric`` finds a baseline (:func:`_mirror_aliases`), but
        # printing them turns three regression scores into six and reads as though
        # ``mae`` and ``mean_absolute_error`` were two different measurements.
        published = {key: value for key, value in scores.items() if key not in ALIASES}
        lines.append(f"  기준선({reference.get('model')}, {reference.get('n_rows_used')}행):")
        lines.append(
            "    "
            + "  ".join(
                f"{key}={value}(chance {chance.get(key, '-')})" for key, value in published.items()
            )
        )
        ci = reference.get("ci")
        if isinstance(ci, dict) and isinstance(ci.get("scores"), dict):
            # The widths, not just the points. A reader who sees f1=0.61 and then a
            # threshold of 0.71 two lines below has no way to tell whether that gap is a
            # target or a rounding error without them.
            unit = "그룹" if ci.get("unit") == "group" else "행"
            lines.append(
                f"    {int(float(ci.get('level') or CI_LEVEL) * 100)}% CI "
                f"({unit} 단위 부트스트랩 {ci.get('resamples')}회): "
                + "  ".join(
                    f"{key}={bound.get('low')}~{bound.get('high')}"
                    for key, bound in ci["scores"].items()
                    if key in published
                )
            )
        ceiling = reference.get("balanced_accuracy_at_best_cut")
        if ceiling is not None:
            lines.append(
                f"    랭킹 KS={reference.get('ks')} → 어떤 컷으로도 "
                f"balanced_accuracy는 {ceiling}이 상한입니다 (이 기준선의 랭킹 기준). "
                "더 높은 바를 원하면 랭킹 자체를 올려야 합니다 — 특성이나 모델 family"
            )
    else:
        lines.append(
            "  기준선: 없음 — 목표 임계값은 지표별 기본값을 씁니다 "
            "(mae·rmse처럼 정답 열의 단위로 나오는 지표는 기본값이 없어 --threshold가 필요합니다)"
        )
    return "\n".join(lines)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a dataset card from raw data.")
    parser.add_argument("--data", required=True, help="path to the CSV to profile")
    parser.add_argument("--target", required=True, help="name of the target column")
    parser.add_argument("--out", required=True, help="where to write the dataset card JSON")
    parser.add_argument(
        "--name",
        default=None,
        help="dataset name for the card (defaults to '<target>-prediction'; the file "
        "name is deliberately not used, since it would put the data source in the prompt)",
    )
    parser.add_argument("--memory-limit-mb", type=float, default=DEFAULT_MEMORY_LIMIT_MB)
    parser.add_argument("--max-train-time-sec", type=float, default=DEFAULT_MAX_TRAIN_TIME_SEC)
    parser.add_argument("--seed", type=int, default=42, help="seed for the baseline split")
    parser.add_argument(
        "--on-missing-target",
        choices=list(TARGET_MISSING_POLICIES),
        default=DEFAULT_TARGET_MISSING_POLICY,
        help="what to do about rows whose target is missing: 'reject' (default) fails and "
        "reports the count, 'drop' removes them and records how many",
    )
    parser.add_argument(
        "--caveat",
        action="append",
        default=[],
        metavar="TEXT",
        dest="caveats",
        help="a fact about this data the card's aggregates cannot show, carried into every "
        "reasoning prompt. Repeatable. This is the only channel for what a human learned by "
        "looking at the raw file — e.g. that a flag with no missing values changes meaning "
        "along row order, so a model leaning on it learns the charting regime, not acuity.",
    )
    parser.add_argument(
        "--group-column",
        default=None,
        metavar="COLUMN",
        help="a column whose rows must not be divided across train/val/test — a patient id "
        "when the table has one row per visit, say. Without it a random split puts the same "
        "patient on both sides and every score in the run is inflated by an amount nothing "
        "in the run can detect. The column is dropped from the features, and the choice is "
        "recorded in the card's private data block so the LLM cannot alter it.",
    )
    parser.add_argument(
        "--no-baseline",
        action="store_true",
        help="skip the reference baseline fit. The card is then thresholdless, so the "
        "goal falls back to the per-metric default.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        card = build_card(
            Path(args.data),
            args.target,
            name=args.name,
            memory_limit_mb=args.memory_limit_mb,
            max_train_time_sec=args.max_train_time_sec,
            baseline=not args.no_baseline,
            seed=args.seed,
            on_missing_target=args.on_missing_target,
            caveats=list(args.caveats or []),
            group_column=args.group_column,
        )
    except (OSError, ValueError, KeyError, ImportError) as exc:
        sys.stderr.write(f"profiling failed: {type(exc).__name__}: {exc}\n")
        return 1

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(card, indent=2, ensure_ascii=False), encoding="utf-8")
    print(summarise(card), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
