"""Fixed training script. Run as an isolated subprocess by ``nodes/training.py``.

This file is *not* generated by an LLM. It is verified code whose behaviour is
driven entirely by the injected config: model name, hyperparameters and data
source. That keeps the execution path deterministic and auditable.

Contract
--------
Input  : ``--config <path>`` (JSON), ``--out <path>`` (where to write result.json),
         optionally ``--score-model <model.joblib>``
Output : ``result.json``::

    {"metrics": {...}, "split": "val" | "test", "applied_hyperparams": {...},
     "dropped_hyperparams": [...], "train_time_sec": float,
     "status": "ok" | "error", "error_type": str | null, "log_tail": str,
     "model_path": str | null}

plus ``model.joblib`` beside it — the fitted pipeline, so the best attempt can be scored
again later without refitting. ``model_path`` is local: it is not in
``privacy.PUBLIC_RESULT_FIELDS``, because a fitted estimator is data-equivalent (an SVC
stores support vectors verbatim).

Two modes, one file. Without ``--score-model`` it fits on the training split and reports
*validation* scores. With it, nothing is fitted: the saved model is scored once on the
test split that :mod:`automl_agent.scoring.splits` held back from the whole run, which is the only
number in the report that no decision was selected against.

``applied_hyperparams`` is what the estimator was really configured with, after the
proposed dict was narrowed to the parameters this model accepts. It, not the proposal,
is what the report and the history digest quote.

``metrics`` carries every registry metric of the target's *task* that the prediction
supports, each one's ``train_`` counterpart that the Critic needs, ``train_val_gap`` on the
goal metric, and on a binary target ``specificity`` plus ``balanced_accuracy_at_best_cut``
and ``cut_headroom``. All four are diagnostics rather than goals — nothing may target them.
The last two say what choosing a decision threshold would have been worth, which is the
question every real LLM run has asked and none could be answered with.

``train_val_gap`` is always *how much worse validation is than training*, not a bare
subtraction: on ``mae`` or ``rmse`` the better score is the smaller one, so a plain
``train - val`` would go negative exactly when the model overfits. Every consumer reads a
positive gap as overfitting, so the sign is normalised here.

The goal metric also gets ``<metric>_ci_low`` / ``<metric>_ci_high``: a 95% bootstrap
interval over the split just scored, resampled by group when the split was grouped. Two
floats rather than a pair because ``privacy.public_result`` keeps only numeric metric
values — see :mod:`automl_agent.scoring.intervals` for what the width does and does not mean.

Exit code is 0 even for training failures (OOM included) so the orchestrator can
treat them as normal flow and hand them to the Critic. The only non-zero exit is
the deliberately simulated hard crash, which exists to prove the orchestrator
survives a dying subprocess.

Config shape
------------
    {
      "model": "hist_gbdt",
      "hyperparams": {"max_iter": 200, "learning_rate": 0.1},
      "preprocessing": {"impute": "median", "scale": true},
      "target_missing": {"policy": "reject" | "drop"},
      "data": {"path": null, "target_column": "target",
               "synthetic": {"n_samples": 5000, "n_features": 20, ...}},
      "metric": "f1",
      "seed": 42,
      "memory_limit_mb": 512,
      "bootstrap": {"resamples": 400},
      "paired_baseline": {"iteration": 3, "path": ".../iter_03/val_predictions.npz"},
      "simulate": {"fail": "oom" | "crash", "sleep_sec": 0}
    }
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time
import traceback
from collections.abc import Sequence
from pathlib import Path
from typing import Any

# The training node runs this file by path, not as a package module, so a relative import
# is impossible and the repo root has to be put on sys.path first. Sharing the registry is
# the point: the metric the goal is derived from and the metric this script emits are then
# the same list, not two lists that agree by hand.
if __package__ in (None, ""):  # pragma: no cover - only when run as a file
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from automl_agent.config import (  # noqa: E402 - needs the path fix above
    MODEL_FILENAME,
    PREDICTIONS_FILENAME,
    SCHEMA_FILENAME,
    file_size_text,
)
from automl_agent.dataset.features import (  # noqa: E402 - needs the path fix above
    append_missing_count,
    append_missing_indicator,
    build_schema,
    describe_drift,
    describe_encoding,
    encode_features,
    encode_with_schema,
)
from automl_agent.dataset.targets import (  # noqa: E402 - needs the path fix above
    DEFAULT_TARGET_MISSING_POLICY,
    detect_task,
    encode_target,
    target_classes,
)
from automl_agent.scoring.calibration import (  # noqa: E402 - needs the path fix above
    measure as calibration_measure,
)
from automl_agent.scoring.intervals import (  # noqa: E402 - needs the path fix above
    DEFAULT_RESAMPLES,
    PAIRED_KEY,
    PAIRED_MEASURED,
    PAIRED_SKIPPED,
    bootstrap_interval,
    describe_interval,
    describe_paired,
    paired_delta,
)
from automl_agent.scoring.metrics import (  # noqa: E402 - needs the path fix above
    ALIASES as METRIC_ALIASES,
)
from automl_agent.scoring.metrics import (  # noqa: E402 - needs the path fix above
    DEFAULT_METRICS,
    METRICS,
    MINIMIZE,
    TASK_CLASSIFICATION,
    TASK_REGRESSION,
    canonical,
    direction_of,
    substitute_metric,
)
from automl_agent.scoring.ranking import (  # noqa: E402 - needs the path fix above
    best_cut_ceiling,
    ks_statistic,
)
from automl_agent.scoring.splits import (  # noqa: E402 - needs the path fix above
    describe_protocol,
    protocol,
    split_three_way,
    val_fingerprint,
)

LOG_TAIL_CHARS = 4000

# Above this, the saved model gets a line of its own in the log. Not a refusal: the score has
# already been earned by the time the file is written, and a run that scored well and then
# deleted its model would be the worse failure. See ``save_model``.
LARGE_MODEL_BYTES = 100 * 1024**2

# The two metrics whose *training-split* counterpart every attempt reports, per task, so the
# Critic can tell underfitting from overfitting whatever the goal metric is. One bounded
# metric and one the goal is usually stated in, on each side.
TRAIN_METRICS: dict[str, tuple[str, ...]] = {
    TASK_CLASSIFICATION: ("f1", "accuracy"),
    TASK_REGRESSION: ("r2", "mae"),
}

# The best cut of this ranking, and how far the achieved score sits from it. Named here
# rather than written as literals at the one call site because the capability list quotes
# both names to the planner as the way to tell a ranking shortfall from an operating-point
# one — see ``capabilities._LEVER_AXES``, which is bound to this tuple by a test. Neither is
# ever targetable: they are measured at a cut the executor will not apply.
CUT_DIAGNOSTICS: tuple[str, str] = ("balanced_accuracy_at_best_cut", "cut_headroom")


class LogBuffer:
    """Collects progress lines; the tail is shipped back inside result.json."""

    def __init__(self) -> None:
        self._lines: list[str] = []

    def write(self, message: str) -> None:
        self._lines.append(message)
        print(message, flush=True)

    def tail(self, limit: int = LOG_TAIL_CHARS) -> str:
        return "\n".join(self._lines)[-limit:]


# --------------------------------------------------------------------------- #
# Data
# --------------------------------------------------------------------------- #


def goal_metric(cfg: dict[str, Any], task: str, log: LogBuffer | None = None) -> str:
    """The metric this attempt is steered by: the configured one, or this task's default.

    The config's metric can fail to belong to the task in two reachable ways, and neither is
    caught upstream by construction: ``RunConfig`` validates the name against the registry
    before profiling, when nobody knows what the target column is, and the orchestrator's
    substitution (:func:`automl_agent.scoring.goal.resolve_goal`) goes by the *card*, while this
    script goes by the column — a card declaring ``regression`` over a column that reads as
    classification puts the mismatch back inside a consistent-looking run.

    Left alone, the consequences are spread out and each one looks like something else: the
    bootstrap interval is skipped ("split too small, or metric degenerate"), the paired
    comparison against the run's best is skipped as ``degenerate``, the overfitting gap is
    measured on a metric nobody chose, and the schema records a goal metric that a labelled
    batch can never be scored against. Substituting once, here, keeps all four on one number.

    Falls back to this task's default rather than to ``f1``: the old literal was a
    classification metric, so on a regression target it was the same mismatch again.
    """
    configured = canonical(str(cfg.get("metric") or "")) or DEFAULT_METRICS[task]
    swap = substitute_metric(task, configured)
    if swap is None:
        return configured if configured in METRICS else DEFAULT_METRICS[task]
    if log is not None:
        log.write(
            f"metric {configured} is not defined for a {task} target: steering by {swap} "
            f"instead, and recording {swap} in the schema so a labelled batch is scored on "
            "the same number"
        )
    return swap


def load_data(
    cfg: dict[str, Any], log: LogBuffer, schema: dict[str, Any] | None = None
) -> tuple[Any, Any, int, Any, str, dict[str, Any] | None]:
    """Return ``(X, y, n_classes, groups, task, schema)`` from a CSV path, or synthesise.

    The agent is given a *dataset card*, not the raw data. When no ``path`` is
    supplied we generate a dataset matching the card's declared shape so the whole
    pipeline is runnable end to end.

    ``groups`` is ``None`` unless ``data.group_column`` names a column, in which case it
    is that column's values aligned to the returned rows — dropped from the features
    first, because an identifier the estimator can read is a shortcut to the label, and a
    numeric one (``subject_id``) would otherwise survive :func:`encode_features` as a
    perfectly ordinary feature.

    ``task`` is read off the target column by :func:`automl_agent.dataset.targets.detect_task` — the
    same function the profiler used when it wrote the card, so the two processes agree about
    what is being predicted without having to be told twice. ``n_classes`` is ``0`` for a
    regression target: there are none, and every consumer here already branches on the task.
    On the synthetic path there is no column to read, so the config's declared ``task``
    decides which generator runs.

    The returned ``schema`` is the encoding that produced ``X`` — the ordered encoded columns,
    each categorical column's levels, and what each class code means — so the caller can save
    it beside the fitted model. ``None`` on the synthetic path, where the matrix is generated
    rather than encoded and there is nothing to replay it on.

    Passing a ``schema`` in reverses the direction: the file is encoded to *that* layout
    instead of to whatever layout it implies on its own. That is what makes a saved model
    scoreable — see :func:`automl_agent.dataset.features.encode_with_schema`. It is used on the
    ``--score-model`` path, where the alternative is re-deriving the layout from a file that
    may no longer be the one the fit saw, and getting a matrix that is silently misaligned
    rather than an error.
    """
    import numpy as np

    data = dict(cfg.get("data") or {})
    path = data.get("path")
    seed = int(cfg.get("seed", 42))
    group_column = data.get("group_column")
    declared_task = str(cfg.get("task") or TASK_CLASSIFICATION)

    if path:
        import pandas as pd

        target = str(data.get("target_column") or "target")
        frame = pd.read_csv(path)
        if target not in frame.columns:
            raise ValueError(f"target_column {target!r} not found in {path}")
        y_series = frame[target]
        group_series = None
        drop = [target]
        if group_column:
            group_column = str(group_column)
            if group_column not in frame.columns:
                raise ValueError(f"group_column {group_column!r} not found in {path}")
            if group_column == target:
                raise ValueError(f"group_column {group_column!r} is the target column")
            group_series = frame[group_column]
            drop.append(group_column)
        # The same encoding the profiler applied before measuring the baseline, from the
        # same function — a bar derived from one feature matrix and scores measured on
        # another are not comparable.
        raw_features = frame.drop(columns=drop)
        if schema is None:
            features, encoding = encode_features(raw_features)
            log.write(describe_encoding(encoding))
            fitted_schema: dict[str, Any] | None = build_schema(raw_features)
        else:
            features, drift = encode_with_schema(raw_features, schema)
            for line in describe_drift(drift):
                log.write(line)
            fitted_schema = dict(schema)
        if features.shape[1] == 0:
            raise ValueError("no usable feature columns remain after dropping the target")
        # Same policy the card recorded, so the profiler's baseline and this score are
        # measured over the same rows. NaN never becomes a class of its own.
        policy = str((cfg.get("target_missing") or {}).get("policy") or DEFAULT_TARGET_MISSING_POLICY)
        task = detect_task(y_series)
        if task != declared_task:
            # Not fatal: the column is the authority and the card is a description of it.
            # Worth a line, because it means the file changed under the card and the
            # baseline the bar came from was measured on the other reading of this column.
            log.write(
                f"target column reads as {task}, but the config declares {declared_task}; "
                "following the column"
            )
        codes, keep, n_missing = encode_target(y_series, policy, task)
        if n_missing:
            features = features[keep]
            if group_series is not None:
                group_series = group_series[keep]
            log.write(f"dropped {n_missing} rows with a missing target (policy={policy})")
        log.write(f"loaded {path}: {features.shape[0]} rows x {features.shape[1]} encoded features")
        groups = None
        if group_series is not None:
            # As text, so a float id and an int id of the same patient are one group and
            # NaN does not silently become a group of one row per NaN.
            groups = group_series.astype("string").fillna("<missing>").to_numpy()
            log.write(f"grouped by {group_column}: {len(set(groups.tolist()))} distinct groups")
        y_codes = codes.to_numpy()
        x_arr = np.asarray(features.to_numpy(), dtype="float64")
        goal = goal_metric(cfg, task, log)
        if fitted_schema is not None:
            # Everything ``predict`` needs that is not in the estimator: which column of the
            # matrix was which, what the numbers coming out of it mean, and which columns the
            # file must not be allowed to supply because the fit never saw them as features.
            fitted_schema.update(
                {
                    "task": task,
                    "target_column": target,
                    "group_column": group_column,
                    "classes": target_classes(y_series, task),
                    "n_features": int(x_arr.shape[1]),
                    "seed": seed,
                    # The metric this run was steered by, so a later labelled batch is scored
                    # on the same number the run was optimised for rather than on whatever
                    # the person scoring the batch happens to pick. Without it, "0.71 on the
                    # holdout, 0.64 here" could be two different measurements.
                    "metric": goal,
                }
            )
        return (
            x_arr,
            y_codes,
            0 if task == TASK_REGRESSION else int(len(set(y_codes.tolist()))),
            groups,
            task,
            fitted_schema,
        )

    syn = dict(data.get("synthetic") or {})
    n_samples = int(syn.get("n_samples", 5000))
    n_features = int(syn.get("n_features", 20))
    n_informative = int(syn.get("n_informative", max(2, n_features // 2)))
    n_informative = min(n_informative, n_features)

    if declared_task == TASK_REGRESSION:
        from sklearn.datasets import make_regression

        x_arr, y_arr = make_regression(
            n_samples=n_samples,
            n_features=n_features,
            n_informative=n_informative,
            # The regression counterpart of ``flip_y``: irreducible error, so a synthetic
            # run cannot reach r2=1.0 and the loop has something to actually converge on.
            noise=float(syn.get("noise", 10.0)),
            random_state=seed,
        )
        log.write(
            f"synthesised regression dataset from card: {n_samples} rows x {n_features} "
            f"features, noise={syn.get('noise', 10.0)}"
        )
        return x_arr, y_arr, 0, None, TASK_REGRESSION, None

    from sklearn.datasets import make_classification

    n_classes = int(syn.get("n_classes", 2))
    weights = syn.get("class_weights")
    x_arr, y_arr = make_classification(
        n_samples=n_samples,
        n_features=n_features,
        n_informative=n_informative,
        n_redundant=max(0, min(n_features - n_informative, int(syn.get("n_redundant", 2)))),
        n_classes=n_classes,
        n_clusters_per_class=int(syn.get("n_clusters_per_class", 2)),
        weights=list(weights) if weights else None,
        class_sep=float(syn.get("class_sep", 0.8)),
        flip_y=float(syn.get("flip_y", 0.03)),
        random_state=seed,
    )
    log.write(
        f"synthesised dataset from card: {n_samples} rows x {n_features} features, "
        f"{n_classes} classes, class_sep={syn.get('class_sep', 0.8)}, flip_y={syn.get('flip_y', 0.03)}"
    )
    return x_arr, y_arr, n_classes, None, TASK_CLASSIFICATION, None


def guard_memory(x_arr: Any, cfg: dict[str, Any], log: LogBuffer) -> None:
    """Raise ``MemoryError`` when the working set would exceed the declared budget.

    A real GPU run would surface CUDA OOM here. On CPU/tabular we enforce an
    explicit budget instead, so the ``oom`` branch is reachable and testable
    rather than hypothetical. ``batch_size`` shrinks the estimate, which is what
    makes the Critic's "reduce batch size" advice actually pay off.
    """
    limit_mb = cfg.get("memory_limit_mb")
    if not limit_mb:
        return
    rows, cols = int(x_arr.shape[0]), int(x_arr.shape[1])
    hyperparams = dict(cfg.get("hyperparams") or {})
    batch = hyperparams.get("batch_size")
    working_rows = min(rows, int(batch)) if isinstance(batch, int) and batch > 0 else rows
    # Tree ensembles and MLPs hold several copies of the working set.
    copies = 4 if cfg.get("model") in {"random_forest", "extra_trees", "gradient_boosting"} else 2
    if str(hyperparams.get("precision", "")).lower() in {"fp16", "float16", "half"}:
        copies = max(1, copies // 2)
    estimate_mb = working_rows * cols * 8 * copies / (1024 * 1024)
    log.write(f"memory estimate {estimate_mb:.1f} MB vs budget {float(limit_mb):.1f} MB")
    if estimate_mb > float(limit_mb):
        raise MemoryError(
            f"out of memory: estimated {estimate_mb:.1f} MB exceeds budget {float(limit_mb):.1f} MB"
        )


# --------------------------------------------------------------------------- #
# Model registry
# --------------------------------------------------------------------------- #

# Hyperparameter names the LLM may plausibly use, mapped to the sklearn names.
ALIASES: dict[str, dict[str, str]] = {
    "hist_gbdt": {"n_estimators": "max_iter", "reg_lambda": "l2_regularization"},
    "mlp": {"learning_rate": "learning_rate_init", "hidden_size": "hidden_layer_sizes"},
    "logreg": {"reg_strength": "C", "epochs": "max_iter"},
    "xgboost": {"lr": "learning_rate", "l2": "reg_lambda"},
    # Ridge's regularisation runs the *opposite* way from LogisticRegression's: alpha is a
    # penalty, C is its inverse. So ``reg_strength`` maps to ``alpha`` here and to ``C``
    # there, and a proposal written in either vocabulary lands on the right knob.
    "ridge": {"reg_strength": "alpha", "l2": "alpha", "lambda": "alpha"},
    "elasticnet": {"reg_strength": "alpha", "l1_ratio": "l1_ratio"},
}

SCALE_SENSITIVE = {"logreg", "mlp", "svc", "knn", "ridge", "linreg", "elasticnet", "svr"}

# Families that route NaN down their own splits, so they are the only ones allowed to skip
# imputation. This is a family check rather than a free choice because ``impute: none`` on
# a linear model is a crash at ``fit``, not a configuration — and because the imputer used
# to be unconditional, which made every plan that reasoned about native NaN handling wrong
# about what it was going to get.
NATIVE_NAN = {"hist_gbdt", "xgboost"}

# Constructor arguments that are valid for the estimator but break at ``fit`` time in
# this harness, so ``set_params`` accepts them and the run dies later. xgboost's
# ``early_stopping_rounds`` needs an ``eval_set``, which a Pipeline cannot forward —
# a plausible proposal that used to cost a whole iteration.
UNSUPPORTED_BY_HARNESS: dict[str, tuple[str, ...]] = {
    "xgboost": ("early_stopping_rounds", "eval_set", "callbacks"),
}


def weight_map(value: dict[Any, Any], labels: Sequence[Any] | None) -> dict[int, float] | None:
    """A ``class_weight`` mapping sklearn will accept, or ``None`` when it will not.

    Two repairs, both of which used to be fatal or silent:

    * **JSON has no integer keys.** The config reaches this script through
      ``train_config.json``, so ``{0: 1, 1: 10}`` arrives as ``{"0": 1, "1": 10}`` and
      sklearn rejects string keys against integer labels.
    * **A label the data does not have raises inside ``fit``**, i.e. after the pipeline is
      built and the memory guard has passed, which costs the whole iteration. Requiring
      exactly one weight per present label turns that into an ordinary dropped
      hyperparameter instead.

    Keys are class *codes*: ``targets.encode_target`` hands training category codes
    (0..n_classes-1, the order of the card's ``class_balance``), not the raw labels.
    """
    if not value:
        return None
    clean: dict[int, float] = {}
    for raw_code, raw_weight in value.items():
        if isinstance(raw_code, bool) or isinstance(raw_weight, bool):
            return None
        try:
            code = int(str(raw_code).strip())
            weight = float(raw_weight)
        except (TypeError, ValueError):
            return None
        if not math.isfinite(weight) or weight <= 0 or code in clean:
            return None
        clean[code] = weight
    if labels is not None and set(clean) != {int(label) for label in labels}:
        return None
    return clean


# LLM spellings → registry keys, per task. Two maps rather than one because a name can mean
# nothing on one side: "logreg" against a continuous target is not a typo worth silently
# repairing into Ridge — it is a proposal that has to be *refused*, so the mistake reaches
# the Critic (and the model_selection node's next choice) instead of being hidden behind a
# substitution the report would then describe as what was asked for.
MODEL_ALIASES: dict[str, dict[str, str]] = {
    TASK_CLASSIFICATION: {
        "logistic_regression": "logreg",
        "logisticregression": "logreg",
        "randomforest": "random_forest",
        "rf": "random_forest",
        "hist_gradient_boosting": "hist_gbdt",
        "histgradientboosting": "hist_gbdt",
        "lightgbm": "hist_gbdt",  # not installed; nearest verified equivalent
        "xgb": "xgboost",
        "neural_net": "mlp",
        "mlp_classifier": "mlp",
    },
    TASK_REGRESSION: {
        "linear_regression": "linreg",
        "linearregression": "linreg",
        "ols": "linreg",
        "ridge_regression": "ridge",
        "ridgeregression": "ridge",
        "elastic_net": "elasticnet",
        "randomforest": "random_forest",
        "rf": "random_forest",
        "hist_gradient_boosting": "hist_gbdt",
        "histgradientboosting": "hist_gbdt",
        "lightgbm": "hist_gbdt",
        "xgb": "xgboost",
        "neural_net": "mlp",
        "mlp_regressor": "mlp",
        "mlpregressor": "mlp",
        "svm": "svr",
    },
}


def _classifier(key: str, seed: int) -> Any:
    """The classifier this key names, or ``None`` if it names none."""
    if key == "logreg":
        from sklearn.linear_model import LogisticRegression

        return LogisticRegression(max_iter=1000, random_state=seed)
    if key == "random_forest":
        from sklearn.ensemble import RandomForestClassifier

        return RandomForestClassifier(n_estimators=300, n_jobs=-1, random_state=seed)
    if key == "extra_trees":
        from sklearn.ensemble import ExtraTreesClassifier

        return ExtraTreesClassifier(n_estimators=300, n_jobs=-1, random_state=seed)
    if key == "hist_gbdt":
        from sklearn.ensemble import HistGradientBoostingClassifier

        return HistGradientBoostingClassifier(random_state=seed)
    if key == "gradient_boosting":
        from sklearn.ensemble import GradientBoostingClassifier

        return GradientBoostingClassifier(random_state=seed)
    if key == "decision_tree":
        from sklearn.tree import DecisionTreeClassifier

        return DecisionTreeClassifier(random_state=seed)
    if key == "knn":
        from sklearn.neighbors import KNeighborsClassifier

        return KNeighborsClassifier()
    if key == "svc":
        from sklearn.svm import SVC

        return SVC(random_state=seed)
    if key == "mlp":
        from sklearn.neural_network import MLPClassifier

        return MLPClassifier(max_iter=400, random_state=seed)
    if key == "xgboost":
        try:
            from xgboost import XGBClassifier
        except ImportError as exc:  # pragma: no cover - reached only if the extra is missing
            raise ValueError(f"model 'xgboost' is unavailable: {exc}") from exc

        return XGBClassifier(
            n_estimators=300, tree_method="hist", eval_metric="logloss", random_state=seed
        )
    return None


def _regressor(key: str, seed: int) -> Any:
    """The regressor this key names, or ``None`` if it names none.

    Deliberately the same keys as :func:`_classifier` wherever the family exists on both
    sides — ``hist_gbdt`` is the same word for both, so a plan written against one card
    reads the same way against the other, and ``capabilities`` publishes one vocabulary.
    """
    if key == "linreg":
        from sklearn.linear_model import LinearRegression

        # No ``random_state``: the closed-form solution has nothing to seed.
        return LinearRegression()
    if key == "ridge":
        from sklearn.linear_model import Ridge

        return Ridge(random_state=seed)
    if key == "elasticnet":
        from sklearn.linear_model import ElasticNet

        return ElasticNet(random_state=seed)
    if key == "random_forest":
        from sklearn.ensemble import RandomForestRegressor

        return RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=seed)
    if key == "extra_trees":
        from sklearn.ensemble import ExtraTreesRegressor

        return ExtraTreesRegressor(n_estimators=300, n_jobs=-1, random_state=seed)
    if key == "hist_gbdt":
        from sklearn.ensemble import HistGradientBoostingRegressor

        return HistGradientBoostingRegressor(random_state=seed)
    if key == "gradient_boosting":
        from sklearn.ensemble import GradientBoostingRegressor

        return GradientBoostingRegressor(random_state=seed)
    if key == "decision_tree":
        from sklearn.tree import DecisionTreeRegressor

        return DecisionTreeRegressor(random_state=seed)
    if key == "knn":
        from sklearn.neighbors import KNeighborsRegressor

        return KNeighborsRegressor()
    if key == "svr":
        from sklearn.svm import SVR

        return SVR()
    if key == "mlp":
        from sklearn.neural_network import MLPRegressor

        return MLPRegressor(max_iter=400, random_state=seed)
    if key == "xgboost":
        try:
            from xgboost import XGBRegressor
        except ImportError as exc:  # pragma: no cover - reached only if the extra is missing
            raise ValueError(f"model 'xgboost' is unavailable: {exc}") from exc

        return XGBRegressor(n_estimators=300, tree_method="hist", random_state=seed)
    return None


def build_estimator(
    name: str,
    hyperparams: dict[str, Any],
    seed: int,
    log: LogBuffer,
    preprocessing: dict[str, Any] | None = None,
    labels: Sequence[Any] | None = None,
    task: str = TASK_CLASSIFICATION,
) -> tuple[Any, dict[str, Any], list[str]]:
    """Instantiate the named model, then apply only the params it actually accepts.

    Unknown keys are dropped and logged rather than raising: the LLM proposes,
    this code validates. That is the reasoning/execution split in practice.

    Returns ``(pipeline, applied, dropped)``. The narrowing used to be visible only in
    ``train.log``, so the report printed the *proposal* and called it the configuration
    that produced the score. Handing both dicts back is what lets the record state what
    actually ran, under the sklearn parameter names it ran under.

    ``task`` selects which of the two estimator families the name is resolved in. A name
    that exists only in the other one raises ``unsupported model``, which
    :func:`classify_exception` turns into an ``unsupported_model`` result — a diagnosable
    outcome, unlike a classifier quietly fitted to a continuous target.
    """
    key = name.strip().lower().replace("-", "_")
    key = MODEL_ALIASES.get(task, {}).get(key, key)

    model = _regressor(key, seed) if task == TASK_REGRESSION else _classifier(key, seed)
    if model is None:
        raise ValueError(f"unsupported model {name!r} for a {task} target")

    mapped: dict[str, Any] = {}
    dropped: list[str] = []
    accepted = model.get_params(deep=False)
    blocked = UNSUPPORTED_BY_HARNESS.get(key, ())
    for raw_key, value in hyperparams.items():
        param = ALIASES.get(key, {}).get(raw_key, raw_key)
        if param in blocked:
            dropped.append(raw_key)
            continue
        if param == "class_weight" and isinstance(value, dict):
            repaired = weight_map(value, labels)
            if repaired is None:
                log.write(f"dropped class_weight={value!r}: not one positive weight per class")
                dropped.append(raw_key)
                continue
            value = repaired
        if param in accepted:
            if param == "hidden_layer_sizes" and isinstance(value, list):
                value = tuple(value)
            mapped[param] = value
        else:
            dropped.append(raw_key)
    if mapped:
        try:
            model.set_params(**mapped)
        except (ValueError, TypeError) as exc:
            log.write(f"rejected hyperparams {mapped}: {exc}; falling back to defaults")
            mapped = {}
    if dropped:
        log.write(f"dropped hyperparams not applicable to {key}: {sorted(dropped)}")
    log.write(f"estimator={key} applied_hyperparams={mapped}")
    return _wrap_preprocessing(key, model, preprocessing or {}, log), mapped, sorted(dropped)


# What the config may ask SimpleImputer for. The planning side validates this too
# (``nodes/training.py::preprocessing_block``); repeating it here is what makes the
# script safe to run against a hand-written config.
IMPUTE_STRATEGIES = ("median", "mean", "most_frequent")
DEFAULT_IMPUTE = "median"
# Not a SimpleImputer strategy — it removes the step entirely. Honoured only for
# :data:`NATIVE_NAN`, so a card can hand a tree the NaNs it knows how to split on instead
# of a median that erases which rows were measured.
IMPUTE_NONE = "none"

# The two columns missingness can become. Both run *before* the imputer, which is the whole
# point: after it there is nothing left to mark. The transformers themselves are
# :func:`automl_agent.dataset.features.append_missing_indicator` and its counterpart — deliberately
# not defined in this module, because this one runs as ``__main__`` and a pickled pipeline
# would record that as the function's home. See the comment there.
MISSING_INDICATOR = "missing_indicator"
MISSING_COUNT = "missing_count"
# Names the executor answers to besides the canonical ones. sklearn calls the parameter
# ``add_indicator`` and the class ``MissingIndicator``, so which name a plan reaches for is
# close to a coin flip, and an unrecognised key is dropped in silence — the plan would then
# describe a column that does not exist. Same purpose as :data:`ALIASES` for hyperparameters.
PREPROCESSING_ALIASES: dict[str, str] = {
    "add_missing_indicators": MISSING_INDICATOR,
    "add_missing_indicator": MISSING_INDICATOR,
    "missing_indicators": MISSING_INDICATOR,
    "add_indicator": MISSING_INDICATOR,
    "missing_counts": MISSING_COUNT,
    "n_missing": MISSING_COUNT,
}


def _wrap_preprocessing(
    key: str, model: Any, preprocessing: dict[str, Any], log: LogBuffer
) -> Any:
    """Build the pipeline the *config* describes, not a fixed one.

    The config used to be written into the artifacts and then ignored here, so a report
    could state "mean imputation" about a run that imputed medians. Absent keys keep the
    old defaults — median, and scaling only where the estimator needs it — so a config
    that says nothing behaves exactly as before.

    ``impute: none`` drops the imputer, and that is the one setting whose validity depends
    on ``key``: only :data:`NATIVE_NAN` families survive a NaN at ``fit``. Asking for it
    anywhere else is downgraded to the default rather than failing the attempt, because a
    plan that guesses wrong about a family should cost a log line, not an iteration. The
    downgrade is logged for the same reason the applied hyperparameters are recorded — the
    alternative is a report describing preprocessing that did not run.
    """
    from sklearn.impute import SimpleImputer
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import FunctionTransformer, StandardScaler

    preprocessing = {
        PREPROCESSING_ALIASES.get(str(name), str(name)): value
        for name, value in preprocessing.items()
    }
    requested = preprocessing.get("impute")
    strategy = DEFAULT_IMPUTE if requested is None else str(requested)
    if strategy == IMPUTE_NONE and key not in NATIVE_NAN:
        log.write(
            f"impute={IMPUTE_NONE} needs a family that splits on NaN "
            f"({', '.join(sorted(NATIVE_NAN))}); {key} does not, using {DEFAULT_IMPUTE}"
        )
        strategy = DEFAULT_IMPUTE
    elif strategy not in (*IMPUTE_STRATEGIES, IMPUTE_NONE):
        log.write(f"unknown impute strategy {requested!r}; using {DEFAULT_IMPUTE}")
        strategy = DEFAULT_IMPUTE

    # An explicit ``scale`` decides; otherwise the estimator does, as before.
    scale = preprocessing.get("scale")
    should_scale = bool(scale) if isinstance(scale, bool) else key in SCALE_SENSITIVE

    steps: list[tuple[str, Any]] = []
    # Before the imputer, in this order. The count runs after the indicator so it counts the
    # original columns only — the appended indicators hold no NaN, so the total is unchanged
    # either way, but the order makes that independence explicit rather than incidental.
    indicate = bool(preprocessing.get(MISSING_INDICATOR))
    count = bool(preprocessing.get(MISSING_COUNT))
    if indicate:
        steps.append((MISSING_INDICATOR, FunctionTransformer(append_missing_indicator)))
    if count:
        steps.append((MISSING_COUNT, FunctionTransformer(append_missing_count)))
    if strategy != IMPUTE_NONE:
        steps.append(("impute", SimpleImputer(strategy=strategy)))
    if should_scale:
        steps.append(("scale", StandardScaler()))
    steps.append(("model", model))
    log.write(
        f"preprocessing applied: impute={strategy} scale={should_scale} "
        f"{MISSING_INDICATOR}={indicate} {MISSING_COUNT}={count}"
    )
    return Pipeline(steps)


def describe_preprocessing(estimator: Any) -> dict[str, Any]:
    """What the pipeline *is*, read off the object rather than recomputed.

    :func:`_wrap_preprocessing` silently downgrades a request it cannot honour — an
    ``impute: none`` outside :data:`NATIVE_NAN` becomes a median, an unknown strategy
    becomes the default — so the config is not a record of what ran. Deriving the answer
    from the config a second time here would be a second code path free to disagree with
    the first; inspecting the built pipeline cannot.

    This exists for the same reason ``applied_hyperparams`` does. Without it a report had
    only the card's ``preprocessing`` block to quote, which is the *card's* default and not
    the plan's override, and one run's write-up duly announced median imputation with
    scaling for an attempt that had run neither.
    """
    steps = getattr(estimator, "named_steps", None)
    if not steps:
        return {}
    imputer = steps.get("impute")
    return {
        "impute": IMPUTE_NONE if imputer is None else str(getattr(imputer, "strategy", "")),
        "scale": "scale" in steps,
        # Reported whether on or off, like ``scale``: a write-up that has to distinguish
        # "no indicators" from "this run predates the field" needs the false, not a gap.
        MISSING_INDICATOR: MISSING_INDICATOR in steps,
        MISSING_COUNT: MISSING_COUNT in steps,
    }


# --------------------------------------------------------------------------- #
# Scoring
# --------------------------------------------------------------------------- #


def scorers(
    y_true: Any, pred: Any, proba: Any, average: str, task: str = TASK_CLASSIFICATION
) -> dict[str, Any]:
    """Thunk per registry metric, so nothing is computed unless it is asked for.

    Also called by ``scripts/profile.py`` — a duplicate of these two branches used to live
    there, and the bar and the scores it is compared against have to be the *same*
    measurement: ``rmse`` differing by a square root between the two files would be a
    comparison nobody could see was wrong. One definition is what makes that drift impossible.

    The regression side is deliberately the *unscaled* metrics: ``mae`` and ``rmse`` come
    back in the target column's own units, which is what makes them readable to someone who
    knows the data — and what makes a portable default bar impossible
    (:func:`automl_agent.scoring.goal.default_bar`).

    sklearn is imported inside the branches so importing this module stays free of it, which
    is what lets the profiler call it without either script paying for the other's estimators.
    """
    if task == TASK_REGRESSION:
        from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

        return {
            "r2": lambda: r2_score(y_true, pred),
            "mae": lambda: mean_absolute_error(y_true, pred),
            # Not ``squared=False``: removed in sklearn 1.6, and
            # ``root_mean_squared_error`` does not exist before 1.4.
            "rmse": lambda: float(mean_squared_error(y_true, pred)) ** 0.5,
        }

    from sklearn.metrics import (
        accuracy_score,
        average_precision_score,
        balanced_accuracy_score,
        f1_score,
        precision_score,
        recall_score,
        roc_auc_score,
    )

    return {
        "f1": lambda: f1_score(y_true, pred, average=average, zero_division=0),
        "accuracy": lambda: accuracy_score(y_true, pred),
        "balanced_accuracy": lambda: balanced_accuracy_score(y_true, pred),
        "precision": lambda: precision_score(y_true, pred, average=average, zero_division=0),
        "recall": lambda: recall_score(y_true, pred, average=average, zero_division=0),
        "roc_auc": lambda: roc_auc_score(y_true, proba),
        "pr_auc": lambda: average_precision_score(y_true, proba),
    }


def score_split(
    names: list[str],
    y_true: Any,
    pred: Any,
    proba: Any,
    average: str,
    log: LogBuffer,
    task: str = TASK_CLASSIFICATION,
) -> dict[str, float]:
    """Score ``names`` on one split, skipping what this prediction cannot support.

    Registry-driven on purpose. Every metric ``--metric`` accepts *for this task* is emitted
    here, so a goal derived for one of them is measured against a number that exists — a
    metric the goal knew about but the result lacked used to read as "never reached the bar".
    """
    thunks = scorers(y_true, pred, proba, average, task)
    scores: dict[str, float] = {}
    for name in names:
        spec = METRICS.get(name)
        if spec is None:  # pragma: no cover - guarded by RunConfig validation
            continue
        if spec.task != task:
            # Not a skip worth logging: the other task's metrics are not missing from this
            # result, they are not defined for it.
            continue
        if spec.binary_only and average != "binary":
            log.write(f"{name} skipped: defined for binary targets only (average={average})")
            continue
        if spec.needs_proba and proba is None:
            continue
        try:
            value = float(thunks[name]())
        except (ValueError, AttributeError) as exc:
            log.write(f"{name} skipped: {exc}")
            continue
        if not math.isfinite(value):
            # sklearn returns NaN instead of raising for some inputs it cannot score —
            # ``roc_auc`` with one class in ``y_true`` is the reachable one. NaN is not a
            # score and it is worse than an absent key: ``json.dumps`` writes it as bare
            # ``NaN``, which is not valid JSON for a strict reader; every comparison against
            # it is False, so a goal check reads "did not reach the bar"; and a prompt or a
            # batch summary prints it as though a measurement had been made.
            log.write(f"{name} skipped: not defined on these rows (returned {value})")
            continue
        scores[name] = value
    return scores


def specificity(y_true: Any, pred: Any) -> float:
    """True-negative rate — recall with the negative class as the positive one.

    Binary only, and deliberately *not* a registry metric: nobody may target it, because a
    model that predicts the majority class for everything scores 1.0. It is emitted for the
    same reason ``train_val_gap`` is — as a diagnostic. ``balanced_accuracy`` is
    ``(recall + specificity) / 2``, so these two numbers are the only thing that names
    which way the imbalance lever has to move, and without them the Critic guesses.
    """
    from sklearn.metrics import recall_score

    return float(recall_score(y_true, pred, pos_label=0, zero_division=0))


def bootstrap_resamples(cfg: dict[str, Any]) -> int:
    """How many resamples the confidence interval gets. ``0`` turns it off.

    Read from the config rather than fixed so a caller with a 500,000-row split has an
    escape hatch, but with no CLI flag: the interval is the difference between "개선됨" and
    "이 행들로는 구분되지 않음", and a knob invites turning it off to make a run look
    decisive. Junk values fall back to the default instead of failing the run.
    """
    raw = dict(cfg.get("bootstrap") or {}).get("resamples", DEFAULT_RESAMPLES)
    if isinstance(raw, bool) or not isinstance(raw, (int, float)):
        return DEFAULT_RESAMPLES
    return max(0, int(raw))


def _proba(model: Any, x_arr: Any, n_classes: int, log: LogBuffer) -> Any:
    """Positive-class probabilities, or None when this model/target cannot give them."""
    if n_classes != 2 or not hasattr(model, "predict_proba"):
        return None
    try:
        return model.predict_proba(x_arr)[:, 1]
    except (ValueError, AttributeError, IndexError) as exc:
        log.write(f"predict_proba unavailable: {exc}")
        return None


# --------------------------------------------------------------------------- #
# Training
# --------------------------------------------------------------------------- #


def evaluate_split(
    model: Any,
    x_eval: Any,
    y_eval: Any,
    n_classes: int,
    average: str,
    log: LogBuffer,
    *,
    task: str = TASK_CLASSIFICATION,
    interval_metric: str | None = None,
    groups: Any = None,
    seed: int = 42,
    resamples: int = DEFAULT_RESAMPLES,
    pred: Any = None,
    proba: Any = None,
) -> dict[str, float]:
    """Every registry metric this prediction supports, plus the binary diagnostics.

    Shared by the validation scoring inside :func:`run_training` and the one-shot test
    scoring in :func:`score_saved_model`, so the two numbers a report puts side by side
    are computed by the same code over different rows.

    ``interval_metric`` names the one metric that also gets a bootstrap confidence interval
    — the goal metric, because it is the number every comparison in the run is made
    against and the cost is linear in metrics times resamples. ``groups`` is the eval
    split's group labels, so a clustered split is resampled by group rather than by row
    (:mod:`automl_agent.scoring.intervals`).

    ``pred``/``proba`` let a caller hand in the predictions instead of having them computed
    here. The one caller that does is :func:`run_training`, which has to *save* the arrays
    for a later attempt to pair against: predicting twice would put two sources under one
    filename, and the file would then describe a pass that nothing was scored on.
    """
    if pred is None:
        pred = model.predict(x_eval)
        proba = _proba(model, x_eval, n_classes, log)
    metrics = score_split(list(METRICS), y_eval, pred, proba, average, log, task)
    for alias, canonical_name in METRIC_ALIASES.items():
        if canonical_name in metrics:
            metrics[alias] = metrics[canonical_name]

    # The other half of balanced_accuracy. Emitted for every binary attempt, not only when
    # balanced_accuracy is the goal, because it costs one more scorer call and it is the
    # number that turns "the operating point is off" into "the weight has to go up".
    if n_classes == 2:
        metrics["specificity"] = round(specificity(y_eval, pred), 6)

    # What choosing the decision threshold would have been worth, in the metric's own
    # units. Every real LLM run has planned a threshold sweep, and the executor cannot do
    # one — but the reason to refuse is quantitative, and nothing was ever measuring it.
    # ``(1 + KS) / 2`` is the best balanced_accuracy any cut of this ranking allows
    # (automl_agent.scoring.ranking), so the difference is exactly the size of the prize. On the
    # MIMIC sample it is +0.0024, which is what turns "the executor will not do that" into
    # "that would buy 0.002; the ranking is where the rest of the gap is".
    #
    # A diagnostic, like specificity and train_val_gap. Never targetable: it is measured
    # at a cut the executor will not apply, so a goal set against it could not be met by
    # anything the harness actually runs.
    ceiling = best_cut_ceiling(ks_statistic(y_eval, proba))
    if ceiling is not None:
        best_cut, headroom = CUT_DIAGNOSTICS
        metrics[best_cut] = ceiling
        if "balanced_accuracy" in metrics:
            metrics[headroom] = round(ceiling - metrics["balanced_accuracy"], 6)

    # Whether the probabilities in the output CSV mean what they say. Every metric above is
    # about the ranking or about the 0/1 call at sklearn's fixed 0.5 cut, and a model can be
    # perfect on both while being systematically overconfident — which matters here precisely
    # because the harness refuses to choose a threshold, so the probability is the part a
    # caller acts on with their own. Diagnostic on the same terms as the two above: measured,
    # reported, never targetable, and never fed back as a recalibration
    # (:mod:`automl_agent.scoring.calibration`).
    if proba is not None:
        metrics.update(calibration_measure(y_eval, proba))

    # How wide the goal metric is on these rows. ``--metric`` only accepts registry keys
    # (``metrics.GOAL_METRICS``), so no alias mirroring is needed here — the interval is
    # published under the same name the goal is stated in.
    target = canonical(interval_metric) if interval_metric else None
    if target and target in metrics:

        def one(y_slice: Any, pred_slice: Any, proba_slice: Any) -> float:
            return float(scorers(y_slice, pred_slice, proba_slice, average, task)[str(target)]())

        interval = bootstrap_interval(
            one, y_eval, pred, proba, groups=groups, seed=seed, resamples=resamples
        )
        if interval is None:
            log.write(f"{target}: no confidence interval (split too small, or metric degenerate)")
        else:
            metrics.update(interval.flatten(target))
            log.write(
                describe_interval(target, metrics[target], interval.bounds)
                + f" — {interval.unit} 단위 재표집 {interval.resamples}회"
            )
    return metrics


def save_model(model: Any, path: Path, log: LogBuffer) -> str | None:
    """Persist the fitted pipeline; return its path, or ``None`` if it could not be written.

    Never fatal. The score has already been earned by the time this runs, and losing the
    run over a full disk would be a worse failure than losing the file. The final holdout
    scoring degrades to "skipped" in that case (``nodes/holdout.py``).

    The file stays inside the run's artifact directory, which ``.gitignore`` blocks, and
    its path is not part of ``privacy.PUBLIC_RESULT_FIELDS``. That is deliberate rather
    than tidy: a fitted ``SVC`` stores its support vectors and a tree stores thresholds
    read off real values, so a model file is data-equivalent and belongs on the private
    side of the boundary with the raw rows.
    """
    try:
        import joblib

        path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(model, path)
    except (OSError, ImportError, TypeError, ValueError) as exc:
        log.write(f"model not saved: {type(exc).__name__}: {exc}")
        return None
    size = path.stat().st_size
    line = f"model saved to {path.name} ({file_size_text(size)})"
    if size > LARGE_MODEL_BYTES:
        # The hyperparameters an iteration was given decide this, and nothing else looks at
        # it: ``guard_memory`` prices the input matrix, which is the same size whatever the
        # estimator does with it. A forest with unbounded depth over 47k rows wrote 486 MB in
        # one iteration of a real run, so on a five-iteration loop the disk is the real limit.
        line += (
            f" — over {file_size_text(LARGE_MODEL_BYTES)}, driven by this iteration's "
            "hyperparameters (tree count and depth, mostly). The run keeps it; the disk is "
            "what bounds a long loop, not memory"
        )
    log.write(line)
    return str(path)




def save_schema(schema: dict[str, Any] | None, path: Path, log: LogBuffer) -> str | None:
    """Persist the encoding the model was fitted with; return its path, or ``None``.

    Never fatal, on the same terms as :func:`save_model`. What is lost without it is narrower
    and worth naming: the model file alone cannot say which column of its input was which, so
    a model saved without its schema can only be applied to rows that happen to encode into
    the same layout — and nothing would check that they had. ``predict`` refuses to run rather
    than guess, which is the point of writing this at all.

    ``None`` schema is not an error: the synthetic path generates its matrix instead of
    encoding a file, so there is no encoding to replay and nothing to write.

    Data-equivalent — category levels and class labels are cell values — so it lands inside
    ``artifacts/`` beside the model and its path stays out of
    ``privacy.PUBLIC_RESULT_FIELDS``.
    """
    if schema is None:
        return None
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(schema, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    except (OSError, TypeError, ValueError) as exc:
        log.write(f"feature schema not saved: {type(exc).__name__}: {exc}")
        return None
    log.write(f"feature schema saved to {path.name} ({len(schema.get('columns') or ())} columns)")
    return str(path)


def load_schema(path: Path, log: LogBuffer) -> dict[str, Any] | None:
    """Read a schema saved beside a model, or ``None`` when there is not one to read.

    ``None`` covers two cases that both have to keep working: a synthetic run, where no
    encoding was ever fitted, and a run from before this file was written. Both fall back to
    re-deriving the layout, which is what they did all along.

    An unreadable or malformed file is *not* silently treated as absent — that would turn a
    corrupted schema into a scoring run whose columns line up by width alone, which is exactly
    the failure this artifact exists to prevent.
    """
    if not path.exists():
        log.write(f"no feature schema beside the model ({path.name}); deriving the encoding from the file")
        return None
    loaded = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise ValueError(f"feature schema {path} is not a JSON object")
    log.write(f"encoding from {path.name}: {len(loaded.get('columns') or ())} columns")
    return loaded


def save_predictions(
    path: Path, pred: Any, proba: Any, fingerprint: str, log: LogBuffer
) -> str | None:
    """Persist this attempt's validation-row predictions, so a later one can pair against it.

    Never fatal, for the same reason :func:`save_model` is not: the score has been earned by
    the time this runs, and the only thing lost is a later attempt's paired verdict, which
    degrades to ``skipped`` with a reason.

    One value per validation row, so this file is data-equivalent in exactly the way
    ``model.joblib`` is, and it stays on the same side of the boundary: written inside
    ``artifacts/``, its *contents* never enter a state channel, and even its path is derived
    from the iteration number rather than carried in one
    (:meth:`automl_agent.config.RunConfig.predictions_path`).

    ``y_val`` is deliberately not in the file. The process that pairs against it has the
    labels already — it just split the same rows — and the fingerprint is what establishes
    that they are the same rows. Storing them would be one more copy of the target column on
    disk buying nothing.
    """
    try:
        import numpy as np

        path.parent.mkdir(parents=True, exist_ok=True)
        arrays: dict[str, Any] = {
            "pred": np.asarray(pred),
            "fingerprint": np.asarray(str(fingerprint)),
        }
        if proba is not None:
            arrays["proba"] = np.asarray(proba)
        np.savez_compressed(path, **arrays)
    except (OSError, ImportError, TypeError, ValueError) as exc:
        log.write(f"val predictions not saved: {type(exc).__name__}: {exc}")
        return None
    log.write(f"val predictions saved to {path.name} ({path.stat().st_size / 1024:.0f} KB)")
    return str(path)


def paired_against_baseline(
    cfg: dict[str, Any],
    y_val: Any,
    pred: Any,
    proba: Any,
    fingerprint: str,
    *,
    metric: str,
    average: str,
    task: str,
    log: LogBuffer,
    groups: Any = None,
    seed: int = 42,
) -> dict[str, Any]:
    """This attempt's goal metric against the run's best so far, as a resampled difference.

    Computed in this process rather than in the node that reads the result, and for the same
    reason ``scripts/train.py`` is a subprocess at all: the orchestrator never imports numpy
    or sklearn, so no node can resample anything. The other option — a second subprocess per
    iteration, the way :mod:`automl_agent.nodes.holdout` scores the test split — would have
    to rebuild this split from the config, and a second derivation is a second thing that can
    disagree with the first. Here ``y_val``, ``pred`` and ``proba`` are the arrays that were
    just scored, so there is nothing to re-derive.

    Always returns a block, and a skipped comparison publishes *why*: "no paired verdict" and
    "the paired verdict found nothing" are different facts, and a reader given silence for
    the first would take it for the second.
    """
    declared = dict(cfg.get("paired_baseline") or {})
    iteration = declared.get("iteration")
    raw_path = declared.get("path")
    block: dict[str, Any] = {"metric": metric, "baseline_iteration": iteration}

    def skipped(reason: str, detail: str = "") -> dict[str, Any]:
        log.write(f"paired comparison skipped ({reason}){f': {detail}' if detail else ''}")
        return {**block, "status": PAIRED_SKIPPED, "reason": reason}

    if not raw_path or iteration is None:
        return skipped("no_baseline")

    import numpy as np

    path = Path(str(raw_path))
    try:
        # ``allow_pickle=False``: this file is written by this script and read by it, and a
        # pickle-bearing npz in the artifact directory would be code execution dressed as a
        # measurement.
        with np.load(path, allow_pickle=False) as loaded:
            stored = str(loaded["fingerprint"])
            base_pred = np.asarray(loaded["pred"])
            base_proba = np.asarray(loaded["proba"]) if "proba" in loaded.files else None
    except (OSError, ValueError, KeyError) as exc:
        return skipped("baseline_missing", f"{path.name}: {type(exc).__name__}: {exc}")

    if stored != fingerprint:
        # The premise of the whole comparison, checked rather than asserted from the seed —
        # see :func:`automl_agent.scoring.splits.val_fingerprint` for what changes the rows without
        # changing the seed.
        return skipped("split_changed", f"{stored[:8]} != {fingerprint[:8]}")

    spec = METRICS.get(metric)
    if spec is not None and spec.needs_proba and (proba is None or base_proba is None):
        return skipped("degenerate", f"{metric} needs probabilities and one side has none")

    def one(y_slice: Any, pred_slice: Any, proba_slice: Any) -> float:
        return float(scorers(y_slice, pred_slice, proba_slice, average, task)[metric]())

    delta = paired_delta(
        one,
        y_val,
        (pred, proba),
        (base_pred, base_proba),
        direction=direction_of(metric),
        groups=groups,
        seed=seed,
        resamples=bootstrap_resamples(cfg),
    )
    if delta is None:
        return skipped("degenerate", f"{metric}: no interval over the difference")
    measured = {
        **block,
        "status": PAIRED_MEASURED,
        "resamples": delta.resamples,
        "unit": delta.unit,
        **delta.flatten(),
    }
    log.write(f"{metric} vs iteration {iteration}: {describe_paired(measured)}")
    return measured


def run_training(
    cfg: dict[str, Any],
    log: LogBuffer,
    model_out: Path | None = None,
    predictions_out: Path | None = None,
    schema_out: Path | None = None,
) -> tuple[
    dict[str, float], dict[str, Any], list[str], dict[str, Any], str | None, dict[str, Any], str | None
]:
    """Fit and score. ``(metrics, applied, dropped, preprocessing, model_path, paired, schema_path)``.

    Three of those seven say what the run was *configured* with rather than what it scored,
    and they are returned rather than re-derived because only this function saw the
    estimator: the config is a request the executor is allowed to narrow. ``paired`` is the
    comparison against the run's best so far, which is empty unless the caller asked for one
    (:func:`paired_against_baseline`). ``schema_path`` is the other half of ``model_path`` —
    the encoding that model was fitted with, without which it can be loaded but not applied.

    Scores are validation-set scores: the test slice
    (:mod:`automl_agent.scoring.splits`) is not read here at all, so nothing the loop selects on
    can have touched it.
    """
    seed = int(cfg.get("seed", 42))
    x_arr, y_arr, n_classes, groups, task, schema = load_data(cfg, log)
    guard_memory(x_arr, cfg, log)
    regression = task == TASK_REGRESSION

    group_column = (cfg.get("data") or {}).get("group_column")
    splits = split_three_way(x_arr, y_arr, seed, groups=groups, stratify=not regression)
    x_train, y_train = splits.x_train, splits.y_train
    x_val, y_val = splits.x_val, splits.y_val
    log.write(
        describe_protocol(protocol(seed, group_column, stratified=not regression))
        + f" {splits.sizes}"
    )

    subsample = (cfg.get("hyperparams") or {}).get("train_subsample")
    if isinstance(subsample, (int, float)) and 0 < float(subsample) < 1:
        keep = max(50, int(len(x_train) * float(subsample)))
        x_train, y_train = x_train[:keep], y_train[:keep]
        log.write(f"train_subsample={subsample} -> {keep} rows")

    model, applied, dropped = build_estimator(
        str(cfg.get("model") or "hist_gbdt"),
        dict(cfg.get("hyperparams") or {}),
        seed,
        log,
        dict(cfg.get("preprocessing") or {}),
        # The labels a ``class_weight`` map has to cover exactly. Taken from the training
        # split, which is what sklearn will validate the map against. ``None`` for a
        # continuous target: there are no classes to weight, and enumerating every distinct
        # value of the column would be both useless and a set of cell values.
        labels=None if regression else sorted(set(y_train.tolist())),
        task=task,
    )
    log.write(f"fitting on {len(x_train)} rows, validating on {len(x_val)} rows")
    model.fit(x_train, y_train)
    model_path = save_model(model, model_out, log) if model_out is not None else None
    # Written after the fit and beside the model, so the file on disk describes the encoding
    # of the matrix this estimator actually saw rather than one derived separately later.
    schema_path = save_schema(schema, schema_out, log) if schema_out is not None else None

    # Silent here: ``load_data`` above already logged the substitution if there was one, and
    # this is the same call with the same task.
    target_metric = goal_metric(cfg, task)
    average = "binary" if n_classes == 2 else "macro"
    pred_train = model.predict(x_train)
    # Predicted once, here, and then both scored and saved. The arrays a later iteration
    # pairs against have to be the arrays this iteration's metrics were computed from, or the
    # file describes a pass nothing was scored on.
    pred_val = model.predict(x_val)
    proba_val = _proba(model, x_val, n_classes, log)
    metrics = evaluate_split(
        model,
        x_val,
        y_val,
        n_classes,
        average,
        log,
        task=task,
        interval_metric=target_metric,
        # The validation split's own group labels, not the whole file's: this interval is
        # about the rows the score was measured on.
        groups=splits.groups_val,
        seed=seed,
        resamples=bootstrap_resamples(cfg),
        pred=pred_val,
        proba=proba_val,
    )

    fingerprint = val_fingerprint(x_val, y_val)
    if predictions_out is not None:
        save_predictions(predictions_out, pred_val, proba_val, fingerprint, log)
    paired = paired_against_baseline(
        cfg,
        y_val,
        pred_val,
        proba_val,
        fingerprint,
        metric=target_metric,
        average=average,
        task=task,
        log=log,
        groups=splits.groups_val,
        seed=seed,
    )

    # Train scores let the Critic tell underfitting from overfitting. The task's two default
    # metrics are part of result.json's shape whatever the goal metric is; the goal metric is
    # added because the gap below has to be about the number the run is judged on.
    train_names = list(TRAIN_METRICS[task])
    if target_metric in METRICS and target_metric not in train_names:
        train_names.append(target_metric)
    train_proba = (
        _proba(model, x_train, n_classes, log)
        if any(METRICS[name].needs_proba for name in train_names)
        else None
    )
    for name, value in score_split(
        train_names, y_train, pred_train, train_proba, average, log, task
    ).items():
        metrics[f"train_{name}"] = value

    # Defined on the goal metric, not on the task's first default: the Critic's
    # overfitting/underfitting branches read this one number, and a gap measured on a metric
    # nobody is optimising sends it the wrong diagnosis. The fallback is for a goal metric
    # with no train counterpart (a probability metric on a model without predict_proba).
    fallback_gap_metric = TRAIN_METRICS[task][0]
    gap_metric = target_metric if f"train_{target_metric}" in metrics else fallback_gap_metric
    if gap_metric in metrics and f"train_{gap_metric}" in metrics:
        # Always "how much worse validation is than training", never a bare subtraction: on a
        # minimize metric the train score is the *smaller* number, so ``train - val`` would be
        # negative exactly when the model is overfitting. Every consumer reads a positive gap
        # as overfitting (``nodes/critic.py``, the Critic prompt's rules), so the direction is
        # applied here — one place — rather than in each of them.
        train_value, val_value = metrics[f"train_{gap_metric}"], metrics[gap_metric]
        worse_by = (
            val_value - train_value
            if direction_of(gap_metric) == MINIMIZE
            else train_value - val_value
        )
        metrics["train_val_gap"] = round(worse_by, 6)
        log.write(f"train_val_gap measured on {gap_metric} ({direction_of(gap_metric)})")

    log.write("metrics: " + json.dumps({k: round(v, 4) for k, v in metrics.items()}))
    return (
        metrics,
        applied,
        dropped,
        describe_preprocessing(model),
        model_path,
        paired,
        schema_path,
    )


def score_saved_model(
    cfg: dict[str, Any], log: LogBuffer, model_path: Path
) -> tuple[dict[str, float], dict[str, Any]]:
    """Score the held-back test split with a model fitted in an earlier process.

    Nothing is fitted here, and nothing but ``x_test`` is predicted on: the point of the
    number is that no decision in the run was made against these rows. The split is
    rebuilt rather than stored, which is safe because it is a pure function of the file,
    the target policy, the group column and the seed — all of which come from the same
    ``train_config.json`` the fit used.

    The preprocessing comes back alongside the metrics because it is read off the loaded
    pipeline: this process never built one, so the config is the only other source and the
    config is a request, not a record.

    The encoding comes off disk too, from the schema saved beside the model, so the test rows
    are encoded into the layout this estimator was fitted on. Re-deriving it from the file
    would agree in the ordinary case and disagree silently in the case worth catching — a file
    edited between the fit and the holdout, whose columns then line up by width alone. A run
    from before schemas were saved has no such file; it is scored the old way, with a line in
    the log saying so.
    """
    import joblib

    seed = int(cfg.get("seed", 42))
    schema = load_schema(model_path.parent / SCHEMA_FILENAME, log)
    x_arr, y_arr, n_classes, groups, task, _schema = load_data(cfg, log, schema)
    splits = split_three_way(
        x_arr, y_arr, seed, groups=groups, stratify=task != TASK_REGRESSION
    )
    model = joblib.load(model_path)
    average = "binary" if n_classes == 2 else "macro"
    log.write(
        f"scoring the held-back test split: {len(splits.y_test)} rows, "
        f"model={model_path.name}"
    )
    metrics = evaluate_split(
        model,
        splits.x_test,
        splits.y_test,
        n_classes,
        average,
        log,
        task=task,
        interval_metric=canonical(str(cfg.get("metric") or "f1")),
        groups=splits.groups_test,
        seed=seed,
        resamples=bootstrap_resamples(cfg),
    )
    log.write("test metrics: " + json.dumps({k: round(v, 4) for k, v in metrics.items()}))
    return metrics, describe_preprocessing(model)


# --------------------------------------------------------------------------- #
# Result plumbing
# --------------------------------------------------------------------------- #


def classify_exception(exc: BaseException) -> str:
    """Map an exception to a coarse ``error_type`` the Critic can reason about."""
    if isinstance(exc, MemoryError):
        return "oom"
    text = f"{type(exc).__name__}: {exc}".lower()
    if any(token in text for token in ("out of memory", "cuda", "cannot allocate", "alloc failed")):
        return "oom"
    if isinstance(exc, (FileNotFoundError, KeyError)) or "not found" in text:
        return "data_issue"
    if isinstance(exc, ValueError) and "unsupported model" in text:
        return "unsupported_model"
    if isinstance(exc, ValueError):
        return "data_issue"
    return "exception"


# Where the non-finite numbers were, when there were any. Private: not in
# ``privacy.PUBLIC_RESULT_FIELDS``, because a reasoning prompt already reads the only thing it
# needs from this — the metric is *absent* from ``metrics``, which the capability list defines
# as "not measured". The list exists for the human reading result.json and the log beside it.
NONFINITE_KEY = "nonfinite_dropped"


def drop_nonfinite(value: Any, path: str = "") -> tuple[Any, list[str]]:
    """``value`` with every non-finite number removed, and the paths of what was removed.

    The last guard before ``result.json`` is written, and it is not the first: ``score_split``
    already refuses to record a metric sklearn answered with NaN, which is where the reachable
    case was found. This one covers the *shape* rather than one producer — a NaN arriving
    through any other key (a paired delta, a train-split score, a future block) would
    otherwise reach the file, and ``json.dumps`` writes it as bare ``NaN``.

    Bare ``NaN`` is not JSON. Python's own ``json.loads`` accepts it, which is exactly why it
    went unnoticed: the orchestrator reads the file back without complaint and the value flows
    into state, where every comparison against it is False — so a goal check reads "did not
    reach the bar" and a report prints it as though a measurement had been made. Anything
    reading the file from outside Python (``jq``, another language) simply fails on it.

    Dropped rather than replaced with ``null``, so the file says the same thing the metrics
    dict says elsewhere: a key that is not there was not measured, and a key with a value in
    it was. ``null`` would add a third state that every reader would have to learn.
    """
    if isinstance(value, dict):
        kept: dict[str, Any] = {}
        dropped: list[str] = []
        for key, item in value.items():
            here = f"{path}.{key}" if path else str(key)
            clean, gone = drop_nonfinite(item, here)
            dropped += gone
            if gone and clean is None and not isinstance(item, (dict, list)):
                continue
            kept[str(key)] = clean
        return kept, dropped
    if isinstance(value, list):
        kept_list: list[Any] = []
        dropped = []
        for index, item in enumerate(value):
            clean, gone = drop_nonfinite(item, f"{path}[{index}]")
            dropped += gone
            # Position matters in a list — an interval is ``[low, high]`` — so a removed
            # element becomes ``null`` instead of shortening the list around it.
            kept_list.append(clean)
        return kept_list, dropped
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return value, []
    if math.isfinite(value):
        return value, []
    return None, [path or "<root>"]


def write_result(
    out_path: Path,
    *,
    status: str,
    metrics: dict[str, Any],
    train_time_sec: float,
    error_type: str | None,
    log_tail: str,
    applied_hyperparams: dict[str, Any] | None = None,
    dropped_hyperparams: list[str] | None = None,
    applied_preprocessing: dict[str, Any] | None = None,
    model_path: str | None = None,
    schema_path: str | None = None,
    paired: dict[str, Any] | None = None,
    split: str = "val",
) -> None:
    payload = {
        "metrics": metrics,
        # Which rows these numbers are about. Always present, because a consumer that
        # cannot tell a validation score from a test score would compare the two as if
        # they meant the same thing.
        "split": split,
        # What the estimator was actually configured with, and what was thrown away on
        # the way. Always present, even on failure (nothing was applied then), so the
        # orchestrator never has to guess whether an absent key means "none" or "old
        # result file".
        "applied_hyperparams": dict(applied_hyperparams or {}),
        "dropped_hyperparams": list(dropped_hyperparams or []),
        # The imputation and scaling the pipeline was built with, which is not always what
        # the config asked for (see :func:`describe_preprocessing`). Empty on failure, when
        # there is no pipeline to describe.
        "applied_preprocessing": dict(applied_preprocessing or {}),
        "train_time_sec": round(float(train_time_sec), 3),
        "status": status,
        "error_type": error_type,
        "log_tail": log_tail,
    }
    if paired:
        # A block of scalars about a *comparison*, not about this model on these rows —
        # which is why it is not folded into ``metrics``. Kept even when it says "skipped",
        # so a reader can tell "not compared, and here is why" from "compared, found nothing".
        payload[PAIRED_KEY] = paired
    if model_path:
        # Local only. Not in ``privacy.PUBLIC_RESULT_FIELDS``, so it never enters a state
        # channel a prompt is rendered from — a fitted model is data-equivalent.
        payload["model_path"] = model_path
    if schema_path:
        # Same terms as ``model_path``, and for the same reason: the levels it lists are cell
        # values. Recorded so a reader of result.json can tell "fitted, and applicable to new
        # rows" from "fitted, and only scoreable on the file it was fitted from".
        payload["schema_path"] = schema_path
    payload, nonfinite = drop_nonfinite(payload)
    if nonfinite:
        payload[NONFINITE_KEY] = nonfinite
        # Into the log tail as well, because that is the field a human reads first and the one
        # the Critic sees on a failed iteration. Appended rather than replacing anything: the
        # exception line, if there is one, is still the more important half.
        payload["log_tail"] = (
            str(payload.get("log_tail") or "")
            + f"\nnon-finite values dropped from result.json: {', '.join(nonfinite)}"
        ).strip()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        # ``allow_nan=False`` is the assertion that the walk above did its job. It is a guard
        # rather than the mechanism: reaching it means a non-finite number arrived in a type
        # the walk does not recognise as a number, which is a bug here and not a bad score.
        text = json.dumps(payload, indent=2, ensure_ascii=False, allow_nan=False)
    except ValueError as exc:
        # A valid file with fewer numbers in it beats an unreadable file: the orchestrator
        # treats a missing result.json as a crashed iteration, which would report this as
        # something the training run did rather than as something this function failed at.
        text = json.dumps(
            {
                "metrics": {},
                "split": split,
                "applied_hyperparams": {},
                "dropped_hyperparams": list(dropped_hyperparams or []),
                "applied_preprocessing": {},
                "train_time_sec": round(float(train_time_sec), 3),
                "status": status,
                "error_type": error_type,
                "log_tail": f"{log_tail}\nresult.json could not be serialised strictly: {exc}",
                NONFINITE_KEY: nonfinite or ["<unknown>"],
            },
            indent=2,
            ensure_ascii=False,
            allow_nan=False,
        )
    out_path.write_text(text, encoding="utf-8")


def apply_simulation(cfg: dict[str, Any], log: LogBuffer) -> None:
    """Deterministic failure injection, used by tests and the OOM/timeout drills."""
    sim = dict(cfg.get("simulate") or {})
    sleep_sec = float(sim.get("sleep_sec", 0) or 0)
    if sleep_sec > 0:
        log.write(f"simulate.sleep_sec={sleep_sec}: sleeping to trigger the orchestrator timeout")
        time.sleep(sleep_sec)
    failure = str(sim.get("fail") or "").lower()
    if failure == "crash":
        # Hard exit without writing result.json: emulates a segfault / CUDA hard
        # failure. Proves the orchestrator survives a dying subprocess.
        log.write("simulate.fail=crash: exiting hard without a result file")
        sys.stderr.write("simulated hard crash in training subprocess\n")
        sys.stderr.flush()
        os._exit(3)
    if failure == "oom":
        raise MemoryError("simulated out of memory during training")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fixed AutoML training script.")
    parser.add_argument("--config", required=True, help="path to the training config JSON")
    parser.add_argument("--out", required=True, help="path to write result.json")
    parser.add_argument(
        "--score-model",
        default=None,
        help=(
            "score the held-back test split with this saved model instead of fitting. "
            "Run once, after the loop, by nodes/holdout.py"
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    out_path = Path(args.out)
    log = LogBuffer()
    started = time.perf_counter()

    try:
        cfg: dict[str, Any] = json.loads(Path(args.config).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        write_result(
            out_path,
            status="error",
            metrics={},
            train_time_sec=time.perf_counter() - started,
            error_type="config_error",
            log_tail=f"failed to read config {args.config}: {exc}",
        )
        return 0

    if args.score_model:
        return _score_only(cfg, Path(args.score_model), out_path, log, started)

    try:
        apply_simulation(cfg, log)
        metrics, applied, dropped, preprocessing, model_path, paired, schema_path = run_training(
            cfg,
            log,
            model_out=out_path.parent / MODEL_FILENAME,
            predictions_out=out_path.parent / PREDICTIONS_FILENAME,
            schema_out=out_path.parent / SCHEMA_FILENAME,
        )
    except BaseException as exc:  # noqa: BLE001 - every failure must become a result
        error_type = classify_exception(exc)
        log.write(f"training failed ({error_type}): {type(exc).__name__}: {exc}")
        log.write(traceback.format_exc(limit=6))
        write_result(
            out_path,
            status="error",
            metrics={},
            train_time_sec=time.perf_counter() - started,
            error_type=error_type,
            log_tail=log.tail(),
        )
        return 0

    write_result(
        out_path,
        status="ok",
        metrics=metrics,
        train_time_sec=time.perf_counter() - started,
        error_type=None,
        log_tail=log.tail(),
        applied_hyperparams=applied,
        dropped_hyperparams=dropped,
        applied_preprocessing=preprocessing,
        model_path=model_path,
        schema_path=schema_path,
        paired=paired,
    )
    return 0


def _score_only(
    cfg: dict[str, Any], model_path: Path, out_path: Path, log: LogBuffer, started: float
) -> int:
    """The ``--score-model`` path: one pass over the test rows, no fitting, no simulation.

    ``apply_simulation`` is deliberately skipped. A card's failure-injection drill belongs
    to the training attempts it was declared for; re-running it here would fail the final
    measurement of a model that had already trained successfully.
    """
    try:
        metrics, preprocessing = score_saved_model(cfg, log, model_path)
    except BaseException as exc:  # noqa: BLE001 - same contract as the training path
        error_type = classify_exception(exc)
        log.write(f"test scoring failed ({error_type}): {type(exc).__name__}: {exc}")
        log.write(traceback.format_exc(limit=6))
        write_result(
            out_path,
            status="error",
            metrics={},
            train_time_sec=time.perf_counter() - started,
            error_type=error_type,
            log_tail=log.tail(),
            split="test",
        )
        return 0

    write_result(
        out_path,
        status="ok",
        metrics=metrics,
        train_time_sec=time.perf_counter() - started,
        error_type=None,
        log_tail=log.tail(),
        applied_preprocessing=preprocessing,
        split="test",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
